// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

type (
	fixture_point_t struct {
		left  int32
		right int32
	}
)

var (
	fixture_make_point func(
		value fixture_point_t,
	) fixture_point_t
	fixture_store_point func(
		value fixture_point_t,
	)
)

func fixture_lib_register_functions(handle uintptr) error {
	fixture_make_point_symbol, err := purego.Dlsym(handle, "fixture_make_point")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_make_point: %w", err)
	}
	purego.RegisterFunc(&fixture_make_point, fixture_make_point_symbol)
	fixture_store_point_symbol, err := purego.Dlsym(handle, "fixture_store_point")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_store_point: %w", err)
	}
	purego.RegisterFunc(&fixture_store_point, fixture_store_point_symbol)
	return nil
}
