// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

type (
	// C: int (*)(void *)
	fixture_fn_a_handler_func = func(uintptr) int32
	// C: void (*)(void *, int)
	fixture_fn_b_handler_func = func(uintptr, int32)
)

func new_fixture_fn_a_handler(fn fixture_fn_a_handler_func) uintptr {
	return uintptr(purego.NewCallback(fn))
}

func new_fixture_fn_b_handler(fn fixture_fn_b_handler_func) uintptr {
	return uintptr(purego.NewCallback(fn))
}

var (
	fixture_fn_a func(
		// C: int (*)(void *)
		handler uintptr,
	)
	fixture_fn_b func(
		// C: void (*)(void *, int)
		handler uintptr,
	)
)

func fixture_fn_a_callbacks(
	handler fixture_fn_a_handler_func,
) {
	handler_callback := uintptr(0)
	if handler != nil {
		handler_callback = purego.NewCallback(handler)
	}
	fixture_fn_a(
		handler_callback,
	)
}
func fixture_fn_b_callbacks(
	handler fixture_fn_b_handler_func,
) {
	handler_callback := uintptr(0)
	if handler != nil {
		handler_callback = purego.NewCallback(handler)
	}
	fixture_fn_b(
		handler_callback,
	)
}

func fixture_lib_register_functions(handle uintptr) error {
	fixture_fn_a_symbol, err := purego.Dlsym(handle, "fixture_fn_a")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_fn_a: %w", err)
	}
	purego.RegisterFunc(&fixture_fn_a, fixture_fn_a_symbol)
	fixture_fn_b_symbol, err := purego.Dlsym(handle, "fixture_fn_b")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_fn_b: %w", err)
	}
	purego.RegisterFunc(&fixture_fn_b, fixture_fn_b_symbol)
	return nil
}
