// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

type (
	// C: enum fixture_mode
	fixture_mode_t = int32
	// C: fixture_mode_t
	fixture_mode_alias_t = int32
	// C: int (*)(int)
	fixture_callback_t = uintptr
	// C: const char *
	fixture_name_t = uintptr
	// C: void *
	fixture_context_t = uintptr
	fixture_point_t   struct {
		left  int32
		right int32
		mode  int32
		_     [4]byte
		// C: const char *
		label uintptr
	}
	fixture_point_alias_t struct {
		left  int32
		right int32
		mode  int32
		_     [4]byte
		// C: const char *
		label uintptr
	}
	fixture_nested_point_t struct {
		point struct {
			left  int32
			right int32
			mode  int32
			_     [4]byte
			// C: const char *
			label uintptr
		}
		inner struct {
			level int32
		}
		_ [4]byte
	}
	fixture_with_array_t struct {
		values [4]int32
	}
	fixture_union_t struct {
		_ [0]int32
		_ [4]byte
	}
	// C: struct fixture_opaque
	fixture_opaque_t struct{}
	// C: int (*)(int)
	fixture_callback_t_func = func(int32) int32
)

func new_fixture_callback_t(fn fixture_callback_t_func) fixture_callback_t {
	return fixture_callback_t(purego.NewCallback(fn))
}

func union_get[T any, U any](u *U) T {
	return *(*T)(unsafe.Pointer(u))
}

func union_set[T any, U any](u *U, v T) {
	*(*T)(unsafe.Pointer(u)) = v
}

const (
	FIXTURE_MODE_OFF = 0
	FIXTURE_MODE_ON  = 1
)
