// Code generated by purego-gen; DO NOT EDIT.

package mylibsys

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

type (
	// C: struct mylib_db
	mylib_db struct{}
	// C: struct mylib_stmt
	mylib_stmt struct{}
	// C: struct mylib_value
	mylib_value struct{}
)
type (
	DB   = mylib_db
	Stmt = mylib_stmt
)

func Malloc(
	size int32,
) uintptr {
	return mylib_malloc(
		size,
	)
}
func Free(
	ptr uintptr,
) {
	mylib_free(
		ptr,
	)
}
func BindInt(
	stmt *Stmt,
	index int32,
	value int32,
) int32 {
	return mylib_bind_int(
		stmt,
		index,
		value,
	)
}

var (
	mylib_malloc func(
		size int32,
		// C: void *
	) uintptr
	mylib_free func(
		// C: void *
		ptr uintptr,
	)
	mylib_db_release_memory func(
		db *mylib_db,
	) int32
	mylib_db_filename func(
		db *mylib_db,
		name string,
	) string
	mylib_bind_int func(
		stmt *mylib_stmt,
		index int32,
		value int32,
	) int32
	mylib_bind_text func(
		stmt *mylib_stmt,
		index int32,
		text string,
		n int32,
	) int32
)

func mylib_register_functions(handle uintptr) error {
	mylib_malloc_symbol, err := purego.Dlsym(handle, "mylib_malloc")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol mylib_malloc: %w", err)
	}
	purego.RegisterFunc(&mylib_malloc, mylib_malloc_symbol)
	mylib_free_symbol, err := purego.Dlsym(handle, "mylib_free")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol mylib_free: %w", err)
	}
	purego.RegisterFunc(&mylib_free, mylib_free_symbol)
	mylib_db_release_memory_symbol, err := purego.Dlsym(handle, "mylib_db_release_memory")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol mylib_db_release_memory: %w", err)
	}
	purego.RegisterFunc(&mylib_db_release_memory, mylib_db_release_memory_symbol)
	mylib_db_filename_symbol, err := purego.Dlsym(handle, "mylib_db_filename")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol mylib_db_filename: %w", err)
	}
	purego.RegisterFunc(&mylib_db_filename, mylib_db_filename_symbol)
	mylib_bind_int_symbol, err := purego.Dlsym(handle, "mylib_bind_int")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol mylib_bind_int: %w", err)
	}
	purego.RegisterFunc(&mylib_bind_int, mylib_bind_int_symbol)
	mylib_bind_text_symbol, err := purego.Dlsym(handle, "mylib_bind_text")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol mylib_bind_text: %w", err)
	}
	purego.RegisterFunc(&mylib_bind_text, mylib_bind_text_symbol)
	return nil
}
