// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

type (
	// C: enum cross_header_demo_error_code
	cross_header_demo_error_code_t int32
)

var (
	cross_header_demo_get_code func(
		result uint64,
	) cross_header_demo_error_code_t
)

func fixture_lib_register_functions(handle uintptr) error {
	cross_header_demo_get_code_symbol, err := purego.Dlsym(handle, "cross_header_demo_get_code")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol cross_header_demo_get_code: %w", err)
	}
	purego.RegisterFunc(&cross_header_demo_get_code, cross_header_demo_get_code_symbol)
	return nil
}
