// Code generated by purego-gen; DO NOT EDIT.

package fixture

const (
	purego_const_ZSTD_VERSION_MAJOR       = 1
	purego_const_ZSTD_VERSION_MINOR       = 5
	purego_const_ZSTD_VERSION_RELEASE     = 7
	purego_const_ZSTD_MAGICNUMBER         = 4247762216
	purego_const_ZSTD_CONTENTSIZE_UNKNOWN = 18446744073709551615
	purego_const_ZSTD_CONTENTSIZE_ERROR   = 18446744073709551614
)
