# Copyright (c) 2026 purego-gen contributors.

"""CLI smoke tests."""

from __future__ import annotations

import os
import shlex
import shutil
import subprocess  # noqa: S404
import sys
from pathlib import Path

from purego_gen.model import (
    TYPE_DIAGNOSTIC_CODE_NO_SUPPORTED_FIELDS,
    TYPE_DIAGNOSTIC_CODE_UNSUPPORTED_BITFIELD,
    TYPE_DIAGNOSTIC_CODE_UNSUPPORTED_FIELD_TYPE,
    TYPE_DIAGNOSTIC_CODE_UNSUPPORTED_UNION_TYPEDEF,
)

_ARGPARSE_USAGE_ERROR = 2
_REPO_ROOT = Path(__file__).resolve().parents[1]
_SRC_DIR = _REPO_ROOT / "src"
_FIXTURES_DIR = _REPO_ROOT / "tests" / "fixtures"
_GOLDEN_DIR = _REPO_ROOT / "tests" / "golden"
_GO_COMPILE_FIXTURE_DIR = _FIXTURES_DIR / "go_compile_module"
_GO_RUNTIME_FIXTURE_DIR = _FIXTURES_DIR / "go_runtime_module"
_RUNTIME_SMOKE_HEADER = _FIXTURES_DIR / "smoke_runtime.h"
_RUNTIME_SMOKE_SOURCE = _FIXTURES_DIR / "smoke_runtime.c"
_GENERATED_HEADER_PREFIX = "// Code generated by purego-gen; DO NOT EDIT."
_NO_SUPPORTED_FIELDS_DIAGNOSTIC_COUNT = 2


def _run_cli(*args: str) -> subprocess.CompletedProcess[str]:
    """Run the CLI via module execution for an end-to-end smoke check.

    Returns:
        Completed process result for assertions.
    """
    env = os.environ.copy()
    existing_pythonpath = env.get("PYTHONPATH")
    src_path = str(_SRC_DIR)
    env["PYTHONPATH"] = (
        src_path if existing_pythonpath is None else f"{src_path}:{existing_pythonpath}"
    )
    return subprocess.run(  # noqa: S603
        [sys.executable, "-m", "purego_gen", *args],
        capture_output=True,
        check=False,
        cwd=_REPO_ROOT,
        env=env,
        text=True,
    )


def _assert_go_source_compiles(source: str, tmp_path: Path) -> None:
    """Compile generated Go source in an isolated temporary module."""
    go_binary = shutil.which("go")
    assert go_binary is not None

    module_dir = tmp_path / "generated"
    shutil.copytree(_GO_COMPILE_FIXTURE_DIR, module_dir)
    (module_dir / "generated.go").write_text(source, encoding="utf-8")

    env = os.environ.copy()

    result = subprocess.run(  # noqa: S603
        [go_binary, "test", "./..."],
        capture_output=True,
        check=False,
        cwd=module_dir,
        env=env,
        text=True,
    )
    assert result.returncode == 0, result.stderr


def _build_runtime_smoke_library(tmp_path: Path) -> Path:
    """Build a tiny C shared library for runtime smoke testing.

    Returns:
        Path to the compiled shared library.
    """
    cc_value = os.environ.get("CC", "").strip()
    if cc_value:
        command = shlex.split(cc_value)
        assert command, "CC is empty after parsing"
    else:
        clang_binary = shutil.which("clang")
        assert clang_binary is not None, "clang is required for runtime smoke tests"
        command = [clang_binary]

    output_name = (
        "libpurego_gen_smoke.dylib" if sys.platform == "darwin" else "libpurego_gen_smoke.so"
    )
    output_path = tmp_path / output_name

    if sys.platform == "darwin":
        command.extend(["-dynamiclib"])
    else:
        command.extend(["-shared", "-fPIC"])
    command.extend(["-o", str(output_path), str(_RUNTIME_SMOKE_SOURCE)])

    result = subprocess.run(  # noqa: S603
        command,
        capture_output=True,
        check=False,
        cwd=_REPO_ROOT,
        text=True,
    )
    assert result.returncode == 0, result.stderr
    return output_path


def _assert_runtime_smoke_passes(source: str, tmp_path: Path, *, shared_library_path: Path) -> None:
    """Run generated bindings against the compiled C shared library."""
    result = _run_runtime_smoke(source, tmp_path, shared_library_path=shared_library_path)
    assert result.returncode == 0, result.stderr


def _run_runtime_smoke(
    source: str, tmp_path: Path, *, shared_library_path: Path
) -> subprocess.CompletedProcess[str]:
    """Run `go test` for runtime smoke fixture and return the process result.

    Returns:
        Completed process result for assertions.
    """
    go_binary = shutil.which("go")
    assert go_binary is not None

    module_dir = tmp_path / "runtime_generated"
    shutil.copytree(_GO_RUNTIME_FIXTURE_DIR, module_dir)
    (module_dir / "generated.go").write_text(source, encoding="utf-8")

    env = os.environ.copy()
    env["CGO_ENABLED"] = "0"
    env["PUREGO_GEN_TEST_LIB"] = str(shared_library_path)

    return subprocess.run(  # noqa: S603
        [go_binary, "test", "./..."],
        capture_output=True,
        check=False,
        cwd=module_dir,
        env=env,
        text=True,
    )


def test_help() -> None:
    """`--help` should succeed and expose top-level usage."""
    result = _run_cli("--help")
    assert result.returncode == 0
    assert "usage: purego-gen" in result.stdout


def test_rejects_subcommand_like_argument() -> None:
    """Single-command CLI should reject unexpected positional command names."""
    header_path = _FIXTURES_DIR / "sample.h"
    result = _run_cli("generate", "--lib-id", "sample_lib", "--header", str(header_path))
    assert result.returncode == _ARGPARSE_USAGE_ERROR
    assert "unrecognized arguments: generate" in result.stderr


def test_generates_golden_output_to_stdout(tmp_path: Path) -> None:
    """CLI should emit gofmt-formatted golden output to stdout."""
    header_path = _FIXTURES_DIR / "sample.h"

    result = _run_cli(
        "--lib-id",
        "sample_lib",
        "--header",
        str(header_path),
        "--pkg",
        "sample",
        "--emit",
        "func,type",
        "--",
        "-I./include",
    )

    expected = (_GOLDEN_DIR / "sample_func_type.go").read_text(encoding="utf-8")
    assert result.returncode == 0
    assert result.stdout == expected
    assert result.stdout.startswith(f"{_GENERATED_HEADER_PREFIX}\n")
    _assert_go_source_compiles(result.stdout, tmp_path)
    assert "generated bindings from function declarations and basic typedefs" in result.stderr


def test_generates_golden_output_to_file(tmp_path: Path) -> None:
    """CLI should emit gofmt-formatted golden output to `--out` path."""
    header_path = _FIXTURES_DIR / "sample.h"
    output_path = tmp_path / "sample_gen.go"

    result = _run_cli(
        "--lib-id",
        "sample_lib",
        "--header",
        str(header_path),
        "--pkg",
        "sample",
        "--emit",
        "func,type",
        "--out",
        str(output_path),
        "--",
        "-I./include",
    )

    expected = (_GOLDEN_DIR / "sample_func_type.go").read_text(encoding="utf-8")
    assert result.returncode == 0
    assert not result.stdout
    assert output_path.read_text(encoding="utf-8") == expected


def test_emits_constants_when_const_category_selected(tmp_path: Path) -> None:
    """`--emit const` should generate compile-time constants only."""
    header_path = _FIXTURES_DIR / "sample_categories.h"

    result = _run_cli(
        "--lib-id",
        "sample_lib",
        "--header",
        str(header_path),
        "--pkg",
        "sample",
        "--emit",
        "const",
    )

    expected = (_GOLDEN_DIR / "sample_const.go").read_text(encoding="utf-8")
    assert result.returncode == 0
    assert result.stdout == expected
    assert "purego_sample_lib_register_functions" not in result.stdout
    assert "purego_sample_lib_load_runtime_vars" not in result.stdout
    _assert_go_source_compiles(result.stdout, tmp_path)


def test_emits_mixed_categories_with_filters(tmp_path: Path) -> None:
    """Category-specific filters should combine with mixed emit selection."""
    header_path = _FIXTURES_DIR / "sample_categories.h"

    result = _run_cli(
        "--lib-id",
        "sample_lib",
        "--header",
        str(header_path),
        "--pkg",
        "sample",
        "--emit",
        "func,const,var",
        "--func-filter",
        "^add$",
        "--const-filter",
        "^SAMPLE_STATUS_OK$",
        "--var-filter",
        "^build_id$",
    )

    expected = (_GOLDEN_DIR / "sample_mixed_filtered.go").read_text(encoding="utf-8")
    assert result.returncode == 0
    assert result.stdout == expected
    _assert_go_source_compiles(result.stdout, tmp_path)


def test_reports_skipped_typedef_diagnostics_for_unsupported_record_fields() -> None:
    """CLI should report skipped typedef diagnostics for unsupported record patterns."""
    header_path = _FIXTURES_DIR / "sample_m3_types.h"

    result = _run_cli(
        "--lib-id",
        "sample_lib",
        "--header",
        str(header_path),
        "--pkg",
        "sample",
        "--emit",
        "type,const",
    )

    assert result.returncode == 0
    assert "skipped typedef sample_with_array_t" in result.stderr
    assert f"[{TYPE_DIAGNOSTIC_CODE_UNSUPPORTED_FIELD_TYPE}]" in result.stderr
    assert "skipped typedef sample_union_t" in result.stderr
    assert f"[{TYPE_DIAGNOSTIC_CODE_UNSUPPORTED_UNION_TYPEDEF}]" in result.stderr
    assert "skipped typedef sample_with_bitfield_t" in result.stderr
    assert f"[{TYPE_DIAGNOSTIC_CODE_UNSUPPORTED_BITFIELD}]" in result.stderr
    assert "skipped typedef sample_with_anonymous_field_t" in result.stderr
    assert "skipped typedef sample_opaque_t" in result.stderr
    assert (
        result.stderr.count(f"[{TYPE_DIAGNOSTIC_CODE_NO_SUPPORTED_FIELDS}]")
        == _NO_SUPPORTED_FIELDS_DIAGNOSTIC_COUNT
    )


def test_fails_when_header_has_parse_errors(tmp_path: Path) -> None:
    """Invalid C headers should fail fast with parse diagnostics."""
    broken_header = tmp_path / "broken_header.h"
    broken_header.write_text("int broken(;\n", encoding="utf-8")

    result = _run_cli(
        "--lib-id",
        "sample_lib",
        "--header",
        str(broken_header),
        "--pkg",
        "sample",
        "--emit",
        "func",
    )

    assert result.returncode == 1
    assert "failed to parse" in result.stderr


def test_fails_when_filter_matches_no_emitted_declarations() -> None:
    """Filters should fail when they match no declaration in emitted categories."""
    header_path = _FIXTURES_DIR / "sample.h"
    result = _run_cli(
        "--lib-id",
        "sample_lib",
        "--header",
        str(header_path),
        "--pkg",
        "sample",
        "--emit",
        "func",
        "--func-filter",
        "^does_not_exist$",
    )

    assert result.returncode == 1
    assert "no declarations matched --func-filter: ^does_not_exist$" in result.stderr


def test_runtime_smoke_with_compiled_shared_library(tmp_path: Path) -> None:
    """Generated bindings should call symbols from a compiled shared C library."""
    shared_library_path = _build_runtime_smoke_library(tmp_path)

    result = _run_cli(
        "--lib-id",
        "sample_lib",
        "--header",
        str(_RUNTIME_SMOKE_HEADER),
        "--pkg",
        "sample",
        "--emit",
        "func,var",
    )

    assert result.returncode == 0, result.stderr
    assert "purego_sample_lib_register_functions" in result.stdout
    assert "purego_sample_lib_load_runtime_vars" in result.stdout
    _assert_runtime_smoke_passes(result.stdout, tmp_path, shared_library_path=shared_library_path)


def test_runtime_smoke_reports_unresolved_symbols(tmp_path: Path) -> None:
    """Runtime smoke should expose unresolved symbol failures from generated code."""
    shared_library_path = _build_runtime_smoke_library(tmp_path)
    header_path = tmp_path / "missing_symbol.h"
    header_path.write_text(
        (
            "extern int smoke_counter;\n"
            "void smoke_reset(void);\n"
            "void smoke_increment(void);\n"
            "void smoke_missing(void);\n"
        ),
        encoding="utf-8",
    )

    result = _run_cli(
        "--lib-id",
        "sample_lib",
        "--header",
        str(header_path),
        "--pkg",
        "sample",
        "--emit",
        "func,var",
    )

    assert result.returncode == 0, result.stderr
    runtime_result = _run_runtime_smoke(
        result.stdout, tmp_path, shared_library_path=shared_library_path
    )
    assert runtime_result.returncode != 0
    combined_output = runtime_result.stdout + runtime_result.stderr
    assert "smoke_missing" in combined_output
