# Copyright (c) 2026 purego-gen contributors.

"""CLI smoke tests."""

from __future__ import annotations

import os
import subprocess  # noqa: S404
import sys
from pathlib import Path

from purego_gen.go_test_harness import run_go_test_in_generated_module
from purego_gen.model import (
    TYPE_DIAGNOSTIC_CODE_NO_SUPPORTED_FIELDS,
    TYPE_DIAGNOSTIC_CODE_UNSUPPORTED_BITFIELD,
    TYPE_DIAGNOSTIC_CODE_UNSUPPORTED_FIELD_TYPE,
    TYPE_DIAGNOSTIC_CODE_UNSUPPORTED_UNION_TYPEDEF,
)
from purego_gen.toolchain import resolve_c_compiler_command

_ARGPARSE_USAGE_ERROR = 2
_REPO_ROOT = Path(__file__).resolve().parents[1]
_SRC_DIR = _REPO_ROOT / "src"
_FIXTURES_DIR = _REPO_ROOT / "tests" / "fixtures"
_GOLDEN_DIR = _REPO_ROOT / "tests" / "golden"
_GO_COMPILE_FIXTURE_DIR = _FIXTURES_DIR / "go_compile_module"
_GO_RUNTIME_FIXTURE_DIR = _FIXTURES_DIR / "go_runtime_module"
_RUNTIME_SMOKE_HEADER = _FIXTURES_DIR / "smoke_runtime.h"
_RUNTIME_SMOKE_SOURCE = _FIXTURES_DIR / "smoke_runtime.c"
_PRIMARY_HEADER = _FIXTURES_DIR / "basic.h"
_CATEGORY_HEADER = _FIXTURES_DIR / "categories.h"
_CONDITIONAL_HEADER = _FIXTURES_DIR / "conditional.h"
_M3_TYPES_HEADER = _FIXTURES_DIR / "abi_types.h"
_FIXTURE_LIB_ID = "sample_lib"
_FIXTURE_PACKAGE = "sample"
_REGISTER_FUNCTIONS_SYMBOL = f"purego_{_FIXTURE_LIB_ID}_register_functions"
_LOAD_RUNTIME_VARS_SYMBOL = f"purego_{_FIXTURE_LIB_ID}_load_runtime_vars"
_GENERATED_HEADER_PREFIX = "// Code generated by purego-gen; DO NOT EDIT."
_NO_SUPPORTED_FIELDS_DIAGNOSTIC_COUNT = 2


def _golden_path(case_id: str) -> Path:
    """Build golden output path for one case id.

    Returns:
        Path to one golden output file.
    """
    return _GOLDEN_DIR / case_id / "generated.go"


def _run_cli(*args: str) -> subprocess.CompletedProcess[str]:
    """Run the CLI via module execution for an end-to-end smoke check.

    Returns:
        Completed process result for assertions.
    """
    env = os.environ.copy()
    existing_pythonpath = env.get("PYTHONPATH")
    src_path = str(_SRC_DIR)
    env["PYTHONPATH"] = (
        src_path if existing_pythonpath is None else f"{src_path}:{existing_pythonpath}"
    )
    return subprocess.run(  # noqa: S603
        [sys.executable, "-m", "purego_gen", *args],
        capture_output=True,
        check=False,
        cwd=_REPO_ROOT,
        env=env,
        text=True,
    )


def _assert_go_source_compiles(source: str, tmp_path: Path) -> None:
    """Compile generated Go source in an isolated temporary module."""
    result = run_go_test_in_generated_module(
        fixture_module_dir=_GO_COMPILE_FIXTURE_DIR,
        tmp_path=tmp_path,
        generated_source=source,
        output_dir_name="generated",
    )
    assert result.returncode == 0, result.stderr


def _build_runtime_smoke_library(tmp_path: Path) -> Path:
    """Build a tiny C shared library for runtime smoke testing.

    Returns:
        Path to the compiled shared library.
    """
    command = resolve_c_compiler_command(purpose="runtime smoke tests")

    output_name = (
        "libpurego_gen_smoke.dylib" if sys.platform == "darwin" else "libpurego_gen_smoke.so"
    )
    output_path = tmp_path / output_name

    if sys.platform == "darwin":
        command.extend(["-dynamiclib"])
    else:
        command.extend(["-shared", "-fPIC"])
    command.extend(["-o", str(output_path), str(_RUNTIME_SMOKE_SOURCE)])

    result = subprocess.run(  # noqa: S603
        command,
        capture_output=True,
        check=False,
        cwd=_REPO_ROOT,
        text=True,
    )
    assert result.returncode == 0, result.stderr
    return output_path


def _assert_runtime_smoke_passes(source: str, tmp_path: Path, *, shared_library_path: Path) -> None:
    """Run generated bindings against the compiled C shared library."""
    result = _run_runtime_smoke(source, tmp_path, shared_library_path=shared_library_path)
    assert result.returncode == 0, result.stderr


def _run_runtime_smoke(
    source: str, tmp_path: Path, *, shared_library_path: Path
) -> subprocess.CompletedProcess[str]:
    """Run `go test` for runtime smoke fixture and return the process result.

    Returns:
        Completed process result for assertions.
    """
    return run_go_test_in_generated_module(
        fixture_module_dir=_GO_RUNTIME_FIXTURE_DIR,
        tmp_path=tmp_path,
        generated_source=source,
        output_dir_name="runtime_generated",
        env_overrides={
            "CGO_ENABLED": "0",
            "PUREGO_GEN_TEST_LIB": str(shared_library_path),
        },
    )


def test_help() -> None:
    """`--help` should succeed and expose top-level usage."""
    result = _run_cli("--help")
    assert result.returncode == 0
    assert "usage: purego-gen" in result.stdout


def test_rejects_subcommand_like_argument() -> None:
    """Single-command CLI should reject unexpected positional command names."""
    header_path = _PRIMARY_HEADER
    result = _run_cli("generate", "--lib-id", _FIXTURE_LIB_ID, "--header", str(header_path))
    assert result.returncode == _ARGPARSE_USAGE_ERROR
    assert "unrecognized arguments: generate" in result.stderr


def test_generates_golden_output_to_stdout(tmp_path: Path) -> None:
    """CLI should emit gofmt-formatted golden output to stdout."""
    header_path = _PRIMARY_HEADER

    result = _run_cli(
        "--lib-id",
        _FIXTURE_LIB_ID,
        "--header",
        str(header_path),
        "--pkg",
        _FIXTURE_PACKAGE,
        "--emit",
        "func,type",
        "--",
        "-I./include",
    )

    expected = _golden_path("case_basic_func_type").read_text(encoding="utf-8")
    assert result.returncode == 0
    assert result.stdout == expected
    assert result.stdout.startswith(f"{_GENERATED_HEADER_PREFIX}\n")
    _assert_go_source_compiles(result.stdout, tmp_path)
    assert "generated bindings from function declarations and basic typedefs" in result.stderr


def test_generates_golden_output_to_file(tmp_path: Path) -> None:
    """CLI should emit gofmt-formatted golden output to `--out` path."""
    header_path = _PRIMARY_HEADER
    output_path = tmp_path / "sample_gen.go"

    result = _run_cli(
        "--lib-id",
        _FIXTURE_LIB_ID,
        "--header",
        str(header_path),
        "--pkg",
        _FIXTURE_PACKAGE,
        "--emit",
        "func,type",
        "--out",
        str(output_path),
        "--",
        "-I./include",
    )

    expected = _golden_path("case_basic_func_type").read_text(encoding="utf-8")
    assert result.returncode == 0
    assert not result.stdout
    assert output_path.read_text(encoding="utf-8") == expected


def test_generates_golden_output_from_multiple_headers(tmp_path: Path) -> None:
    """CLI should keep deterministic output when multiple headers are provided."""
    header_path_a = _PRIMARY_HEADER
    header_path_b = _CATEGORY_HEADER

    result = _run_cli(
        "--lib-id",
        _FIXTURE_LIB_ID,
        "--header",
        str(header_path_a),
        "--header",
        str(header_path_b),
        "--pkg",
        _FIXTURE_PACKAGE,
        "--emit",
        "func,type,const,var",
        "--",
        "-I./include",
    )

    expected = _golden_path("case_basic_and_categories").read_text(encoding="utf-8")
    assert result.returncode == 0
    assert result.stdout == expected
    _assert_go_source_compiles(result.stdout, tmp_path)


def test_emits_constants_when_const_category_selected(tmp_path: Path) -> None:
    """`--emit const` should generate compile-time constants only."""
    header_path = _CATEGORY_HEADER

    result = _run_cli(
        "--lib-id",
        _FIXTURE_LIB_ID,
        "--header",
        str(header_path),
        "--pkg",
        _FIXTURE_PACKAGE,
        "--emit",
        "const",
    )

    expected = _golden_path("case_categories_const").read_text(encoding="utf-8")
    assert result.returncode == 0
    assert result.stdout == expected
    assert _REGISTER_FUNCTIONS_SYMBOL not in result.stdout
    assert _LOAD_RUNTIME_VARS_SYMBOL not in result.stdout
    _assert_go_source_compiles(result.stdout, tmp_path)


def test_generates_conditional_golden_output_with_clang_define(tmp_path: Path) -> None:
    """Clang `-D` args should deterministically change emitted declarations."""
    header_path = _CONDITIONAL_HEADER

    result_off = _run_cli(
        "--lib-id",
        _FIXTURE_LIB_ID,
        "--header",
        str(header_path),
        "--pkg",
        _FIXTURE_PACKAGE,
        "--emit",
        "func,var",
    )
    result_on = _run_cli(
        "--lib-id",
        _FIXTURE_LIB_ID,
        "--header",
        str(header_path),
        "--pkg",
        _FIXTURE_PACKAGE,
        "--emit",
        "func,var",
        "--",
        "-DFIXTURE_ENABLE_EXTRA",
    )

    expected_off = _golden_path("case_conditional_default").read_text(encoding="utf-8")
    expected_on = _golden_path("case_conditional_with_define").read_text(encoding="utf-8")
    assert result_off.returncode == 0
    assert result_on.returncode == 0
    assert result_off.stdout == expected_off
    assert result_on.stdout == expected_on
    assert result_off.stdout != result_on.stdout
    _assert_go_source_compiles(result_off.stdout, tmp_path / "off")
    _assert_go_source_compiles(result_on.stdout, tmp_path / "on")


def test_emits_mixed_categories_with_filters(tmp_path: Path) -> None:
    """Category-specific filters should combine with mixed emit selection."""
    header_path = _CATEGORY_HEADER

    result = _run_cli(
        "--lib-id",
        _FIXTURE_LIB_ID,
        "--header",
        str(header_path),
        "--pkg",
        _FIXTURE_PACKAGE,
        "--emit",
        "func,const,var",
        "--func-filter",
        "^add$",
        "--const-filter",
        "^FIXTURE_STATUS_OK$",
        "--var-filter",
        "^build_id$",
    )

    expected = _golden_path("case_categories_mixed_filtered").read_text(encoding="utf-8")
    assert result.returncode == 0
    assert result.stdout == expected
    _assert_go_source_compiles(result.stdout, tmp_path)


def test_reports_skipped_typedef_diagnostics_for_unsupported_record_fields() -> None:
    """CLI should report skipped typedef diagnostics for unsupported record patterns."""
    header_path = _M3_TYPES_HEADER

    result = _run_cli(
        "--lib-id",
        _FIXTURE_LIB_ID,
        "--header",
        str(header_path),
        "--pkg",
        _FIXTURE_PACKAGE,
        "--emit",
        "type,const",
    )

    assert result.returncode == 0
    assert "skipped typedef fixture_with_array_t" in result.stderr
    assert f"[{TYPE_DIAGNOSTIC_CODE_UNSUPPORTED_FIELD_TYPE}]" in result.stderr
    assert "skipped typedef fixture_union_t" in result.stderr
    assert f"[{TYPE_DIAGNOSTIC_CODE_UNSUPPORTED_UNION_TYPEDEF}]" in result.stderr
    assert "skipped typedef fixture_with_bitfield_t" in result.stderr
    assert f"[{TYPE_DIAGNOSTIC_CODE_UNSUPPORTED_BITFIELD}]" in result.stderr
    assert "skipped typedef fixture_with_anonymous_field_t" in result.stderr
    assert "skipped typedef fixture_opaque_t" in result.stderr
    assert (
        result.stderr.count(f"[{TYPE_DIAGNOSTIC_CODE_NO_SUPPORTED_FIELDS}]")
        == _NO_SUPPORTED_FIELDS_DIAGNOSTIC_COUNT
    )


def test_fails_when_header_has_parse_errors(tmp_path: Path) -> None:
    """Invalid C headers should fail fast with parse diagnostics."""
    broken_header = tmp_path / "broken_header.h"
    broken_header.write_text("int broken(;\n", encoding="utf-8")

    result = _run_cli(
        "--lib-id",
        _FIXTURE_LIB_ID,
        "--header",
        str(broken_header),
        "--pkg",
        _FIXTURE_PACKAGE,
        "--emit",
        "func",
    )

    assert result.returncode == 1
    assert "failed to parse" in result.stderr


def test_fails_when_filter_matches_no_emitted_declarations() -> None:
    """Filters should fail when they match no declaration in emitted categories."""
    header_path = _PRIMARY_HEADER
    result = _run_cli(
        "--lib-id",
        _FIXTURE_LIB_ID,
        "--header",
        str(header_path),
        "--pkg",
        _FIXTURE_PACKAGE,
        "--emit",
        "func",
        "--func-filter",
        "^does_not_exist$",
    )

    assert result.returncode == 1
    assert "no declarations matched --func-filter: ^does_not_exist$" in result.stderr


def test_runtime_smoke_with_compiled_shared_library(tmp_path: Path) -> None:
    """Generated bindings should call symbols from a compiled shared C library."""
    shared_library_path = _build_runtime_smoke_library(tmp_path)

    result = _run_cli(
        "--lib-id",
        _FIXTURE_LIB_ID,
        "--header",
        str(_RUNTIME_SMOKE_HEADER),
        "--pkg",
        _FIXTURE_PACKAGE,
        "--emit",
        "func",
    )

    assert result.returncode == 0, result.stderr
    assert _REGISTER_FUNCTIONS_SYMBOL in result.stdout
    _assert_runtime_smoke_passes(result.stdout, tmp_path, shared_library_path=shared_library_path)


def test_runtime_smoke_reports_unresolved_symbols(tmp_path: Path) -> None:
    """Runtime smoke should expose unresolved symbol failures from generated code."""
    shared_library_path = _build_runtime_smoke_library(tmp_path)
    header_path = tmp_path / "missing_symbol.h"
    header_path.write_text(
        (
            "int smoke_reset(void);\n"
            "int smoke_increment(void);\n"
            "int smoke_get_counter(void);\n"
            "void smoke_missing(void);\n"
        ),
        encoding="utf-8",
    )

    result = _run_cli(
        "--lib-id",
        _FIXTURE_LIB_ID,
        "--header",
        str(header_path),
        "--pkg",
        _FIXTURE_PACKAGE,
        "--emit",
        "func",
    )

    assert result.returncode == 0, result.stderr
    runtime_result = _run_runtime_smoke(
        result.stdout, tmp_path, shared_library_path=shared_library_path
    )
    assert runtime_result.returncode != 0
    combined_output = runtime_result.stdout + runtime_result.stderr
    assert "smoke_missing" in combined_output
