# Copyright (c) 2026 purego-gen contributors.

"""CLI smoke tests."""

from __future__ import annotations

import os
import subprocess  # noqa: S404
import sys
from pathlib import Path

_ARGPARSE_USAGE_ERROR = 2
_REPO_ROOT = Path(__file__).resolve().parents[1]
_SRC_DIR = _REPO_ROOT / "src"


def _run_cli(*args: str) -> subprocess.CompletedProcess[str]:
    """Run the CLI via module execution for an end-to-end smoke check.

    Returns:
        Completed process result for assertions.
    """
    env = os.environ.copy()
    existing_pythonpath = env.get("PYTHONPATH")
    src_path = str(_SRC_DIR)
    env["PYTHONPATH"] = (
        src_path if existing_pythonpath is None else f"{src_path}:{existing_pythonpath}"
    )
    return subprocess.run(  # noqa: S603
        [sys.executable, "-m", "purego_gen", *args],
        capture_output=True,
        check=False,
        cwd=_REPO_ROOT,
        env=env,
        text=True,
    )


def test_help() -> None:
    """`--help` should succeed and expose top-level usage."""
    result = _run_cli("--help")
    assert result.returncode == 0
    assert "usage: purego-gen" in result.stdout


def test_rejects_subcommand_like_argument() -> None:
    """Single-command CLI should reject unexpected positional command names."""
    result = _run_cli("generate", "--lib-id", "zstd", "--header", "zstd.h")
    assert result.returncode == _ARGPARSE_USAGE_ERROR
    assert "unrecognized arguments: generate" in result.stderr


def test_generates_stub_to_stdout() -> None:
    """Minimal invocation should produce deterministic stub output."""
    result = _run_cli(
        "--lib-id",
        "zstd",
        "--header",
        "zstd.h",
        "--pkg",
        "zstd",
        "--",
        "-I./include",
    )
    assert result.returncode == 0
    assert "// Code generated by purego-gen; DO NOT EDIT." in result.stdout
    assert "package zstd" in result.stdout
    assert "func purego_zstd_register_functions(handle uintptr) error" in result.stdout
    assert "func purego_zstd_load_runtime_vars(handle uintptr) error" in result.stdout
    assert "generated placeholder bindings" in result.stderr
