// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

var (
	fixture_compress_with_dict func(
		// C: void *
		dst uintptr,
		dst_cap uint64,
		// C: const void *
		src uintptr,
		src_size uint64,
		// C: const void *
		dict uintptr,
		dict_size uint64,
	) int32
)

func fixture_compress_with_dict_bytes(
	dst uintptr,
	dst_cap uint64,
	src []byte,
	dict []byte,
) int32 {
	src_ptr := uintptr(0)
	src_len := src
	dict_ptr := uintptr(0)
	dict_len := dict
	if len(src_len) > 0 {
		src_ptr = uintptr(unsafe.Pointer(&src_len[0]))
	}
	if len(dict_len) > 0 {
		dict_ptr = uintptr(unsafe.Pointer(&dict_len[0]))
	}
	return fixture_compress_with_dict(
		dst,
		dst_cap,
		src_ptr,
		uint64(len(src_len)),
		dict_ptr,
		uint64(len(dict_len)),
	)
}

func fixture_lib_register_functions(handle uintptr) error {
	fixture_compress_with_dict_symbol, err := purego.Dlsym(handle, "fixture_compress_with_dict")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_compress_with_dict: %w", err)
	}
	purego.RegisterFunc(&fixture_compress_with_dict, fixture_compress_with_dict_symbol)
	return nil
}
