// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

type (
	// C: enum fixture_status
	fixture_status_t = int32
)

var (
	fixture_query func() int32
)

func fixture_lib_register_functions(handle uintptr) error {
	fixture_query_symbol, err := purego.Dlsym(handle, "fixture_query")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_query: %w", err)
	}
	purego.RegisterFunc(&fixture_query, fixture_query_symbol)
	return nil
}
