// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

type (
	// C: int
	purego_gen_fixture_mode_t = int32
)

const (
	purego_gen_FIXTURE_STATUS_OK = 0
)

var (
	purego_gen_add func(
		lhs int32,
		rhs int32,
	) int32
)

func purego_gen_fixture_lib_register_functions(handle uintptr) error {
	purego_gen_add_symbol, err := purego.Dlsym(handle, "add")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol add: %w", err)
	}
	purego.RegisterFunc(&purego_gen_add, purego_gen_add_symbol)
	return nil
}

var (
	purego_gen_fixture_counter uintptr
)

func purego_gen_fixture_lib_load_runtime_vars(handle uintptr) error {
	purego_gen_fixture_counter_symbol, err := purego.Dlsym(handle, "fixture_counter")
	if err != nil {
		return fmt.Errorf(
			"purego-gen: failed to resolve runtime var symbol fixture_counter: %w",
			err,
		)
	}
	purego_gen_fixture_counter = purego_gen_fixture_counter_symbol
	return nil
}
