// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

var (
	fixture_set_status func(
		value int32,
	) int32
)

func fixture_lib_register_functions(handle uintptr) error {
	fixture_set_status_symbol, err := purego.Dlsym(handle, "fixture_set_status")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_set_status: %w", err)
	}
	purego.RegisterFunc(&fixture_set_status, fixture_set_status_symbol)
	return nil
}
