// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

type (
	// C: int (*)(void *, int, char **)
	fixture_cb_t = uintptr
	// C: int (*)(void *, int, char **)
	fixture_cb_t_func = func(uintptr, int32, uintptr) int32
	// C: int (*)(void *, int, char **)
	callback_func = func(uintptr, int32, uintptr) int32
)

func new_fixture_cb_t(fn fixture_cb_t_func) fixture_cb_t {
	return fixture_cb_t(purego.NewCallback(fn))
}

func new_callback(fn callback_func) uintptr {
	return uintptr(purego.NewCallback(fn))
}

var (
	fixture_register func(
		callback fixture_cb_t,
	) int32
)

func fixture_register_callbacks(
	callback callback_func,
) int32 {
	callback_callback := uintptr(0)
	if callback != nil {
		callback_callback = purego.NewCallback(callback)
	}
	return fixture_register(
		callback_callback,
	)
}

func fixture_lib_register_functions(handle uintptr) error {
	fixture_register_symbol, err := purego.Dlsym(handle, "fixture_register")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_register: %w", err)
	}
	purego.RegisterFunc(&fixture_register, fixture_register_symbol)
	return nil
}
