// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

type (
	purego_type_sqlite3                 struct{}  // struct sqlite3
	purego_type_sqlite3_int64           = int64   // sqlite_int64
	purego_type_sqlite3_callback        = uintptr // int (*)(void *, int, char **, char **)
	purego_type_sqlite3_stmt            struct{}  // struct sqlite3_stmt
	purego_type_sqlite3_value           struct{}  // struct sqlite3_value
	purego_type_sqlite3_context         struct{}  // struct sqlite3_context
	purego_type_sqlite3_destructor_type = uintptr // void (*)(void *)
)

const (
	purego_const_SQLITE_OK                                                 = 0
	purego_const_SQLITE_ERROR                                              = 1
	purego_const_SQLITE_ROW                                                = 100
	purego_const_SQLITE_DONE                                               = 101
	purego_const_SQLITE_OPEN_READONLY                                      = 1
	purego_const_SQLITE_OPEN_READWRITE                                     = 2
	purego_const_SQLITE_OPEN_CREATE                                        = 4
	purego_const_SQLITE_OPEN_URI                                           = 64
	purego_const_SQLITE_OPEN_MEMORY                                        = 128
	purego_const_SQLITE_OPEN_NOMUTEX                                       = 32768
	purego_const_SQLITE_OPEN_FULLMUTEX                                     = 65536
	purego_const_SQLITE_INSERT                                             = 18
	purego_const_SQLITE_TRACE_STMT                                         = 1
	purego_const_SQLITE_TRACE_ROW                                          = 4
	purego_const_SQLITE_INTEGER                                            = 1
	purego_const_SQLITE_FLOAT                                              = 2
	purego_const_SQLITE_BLOB                                               = 4
	purego_const_SQLITE_NULL                                               = 5
	purego_const_SQLITE_TEXT                                               = 3
	purego_const_SQLITE_UTF8                                               = 1
	purego_const_SQLITE_UTF16                                              = 4
	purego_const_SQLITE_STATIC         purego_type_sqlite3_destructor_type = 0
	purego_const_SQLITE_TRANSIENT      purego_type_sqlite3_destructor_type = ^uintptr(0)
)

var (
	purego_func_sqlite3_libversion func() string
	purego_func_sqlite3_close      func(
		arg1 *purego_type_sqlite3,
	) int32
	purego_func_sqlite3_close_v2 func(
		arg1 *purego_type_sqlite3,
	) int32
	purego_func_sqlite3_exec func(
		arg1 *purego_type_sqlite3,
		sql string,
		callback purego_type_sqlite3_callback,
		arg4 uintptr, // void *
		errmsg uintptr, // char **
	) int32
	purego_func_sqlite3_last_insert_rowid func(
		arg1 *purego_type_sqlite3,
	) int64
	purego_func_sqlite3_changes64 func(
		arg1 *purego_type_sqlite3,
	) int64
	purego_func_sqlite3_busy_timeout func(
		arg1 *purego_type_sqlite3,
		ms int32,
	) int32
	purego_func_sqlite3_trace_v2 func(
		arg1 *purego_type_sqlite3,
		uMask uint32,
		xCallback uintptr, // int (*)(unsigned int, void *, void *, void *)
		pCtx uintptr, // void *
	) int32
	purego_func_sqlite3_progress_handler func(
		arg1 *purego_type_sqlite3,
		arg2 int32,
		arg3 uintptr, // int (*)(void *)
		arg4 uintptr, // void *
	)
	purego_func_sqlite3_open func(
		filename string,
		ppDb **purego_type_sqlite3,
	) int32
	purego_func_sqlite3_open_v2 func(
		filename string,
		ppDb **purego_type_sqlite3,
		flags int32,
		zVfs string,
	) int32
	purego_func_sqlite3_extended_errcode func(
		db *purego_type_sqlite3,
	) int32
	purego_func_sqlite3_errmsg func(
		arg1 *purego_type_sqlite3,
	) string
	purego_func_sqlite3_prepare_v2 func(
		db *purego_type_sqlite3,
		zSql string,
		nByte int32,
		ppStmt **purego_type_sqlite3_stmt,
		pzTail uintptr, // const char **
	) int32
	purego_func_sqlite3_bind_blob func(
		arg1 *purego_type_sqlite3_stmt,
		arg2 int32,
		arg3 uintptr, // const void *
		n int32,
		arg5 purego_type_sqlite3_destructor_type,
	) int32
	purego_func_sqlite3_bind_double func(
		arg1 *purego_type_sqlite3_stmt,
		arg2 int32,
		arg3 float64,
	) int32
	purego_func_sqlite3_bind_int64 func(
		arg1 *purego_type_sqlite3_stmt,
		arg2 int32,
		arg3 int64,
	) int32
	purego_func_sqlite3_bind_null func(
		arg1 *purego_type_sqlite3_stmt,
		arg2 int32,
	) int32
	purego_func_sqlite3_bind_text func(
		arg1 *purego_type_sqlite3_stmt,
		arg2 int32,
		arg3 string,
		arg4 int32,
		arg5 purego_type_sqlite3_destructor_type,
	) int32
	purego_func_sqlite3_clear_bindings func(
		arg1 *purego_type_sqlite3_stmt,
	) int32
	purego_func_sqlite3_column_count func(
		pStmt *purego_type_sqlite3_stmt,
	) int32
	purego_func_sqlite3_step func(
		arg1 *purego_type_sqlite3_stmt,
	) int32
	purego_func_sqlite3_column_blob func(
		arg1 *purego_type_sqlite3_stmt,
		iCol int32,
	) uintptr // const void *
	purego_func_sqlite3_column_double func(
		arg1 *purego_type_sqlite3_stmt,
		iCol int32,
	) float64
	purego_func_sqlite3_column_int func(
		arg1 *purego_type_sqlite3_stmt,
		iCol int32,
	) int32
	purego_func_sqlite3_column_int64 func(
		arg1 *purego_type_sqlite3_stmt,
		iCol int32,
	) int64
	purego_func_sqlite3_column_text func(
		arg1 *purego_type_sqlite3_stmt,
		iCol int32,
	) string
	purego_func_sqlite3_column_bytes func(
		arg1 *purego_type_sqlite3_stmt,
		iCol int32,
	) int32
	purego_func_sqlite3_column_type func(
		arg1 *purego_type_sqlite3_stmt,
		iCol int32,
	) int32
	purego_func_sqlite3_finalize func(
		pStmt *purego_type_sqlite3_stmt,
	) int32
	purego_func_sqlite3_reset func(
		pStmt *purego_type_sqlite3_stmt,
	) int32
	purego_func_sqlite3_create_function func(
		db *purego_type_sqlite3,
		zFunctionName string,
		nArg int32,
		eTextRep int32,
		pApp uintptr, // void *
		xFunc uintptr, // void (*)(sqlite3_context *, int, sqlite3_value **)
		xStep uintptr, // void (*)(sqlite3_context *, int, sqlite3_value **)
		xFinal uintptr, // void (*)(sqlite3_context *)
	) int32
	purego_func_sqlite3_create_function16 func(
		db *purego_type_sqlite3,
		zFunctionName uintptr, // const void *
		nArg int32,
		eTextRep int32,
		pApp uintptr, // void *
		xFunc uintptr, // void (*)(sqlite3_context *, int, sqlite3_value **)
		xStep uintptr, // void (*)(sqlite3_context *, int, sqlite3_value **)
		xFinal uintptr, // void (*)(sqlite3_context *)
	) int32
	purego_func_sqlite3_create_function_v2 func(
		db *purego_type_sqlite3,
		zFunctionName string,
		nArg int32,
		eTextRep int32,
		pApp uintptr, // void *
		xFunc uintptr, // void (*)(sqlite3_context *, int, sqlite3_value **)
		xStep uintptr, // void (*)(sqlite3_context *, int, sqlite3_value **)
		xFinal uintptr, // void (*)(sqlite3_context *)
		xDestroy purego_type_sqlite3_destructor_type,
	) int32
	purego_func_sqlite3_value_int func(
		arg1 *purego_type_sqlite3_value,
	) int32
	purego_func_sqlite3_value_text func(
		arg1 *purego_type_sqlite3_value,
	) string
	purego_func_sqlite3_user_data func(
		arg1 *purego_type_sqlite3_context,
	) uintptr // void *
	purego_func_sqlite3_result_int func(
		arg1 *purego_type_sqlite3_context,
		arg2 int32,
	)
	purego_func_sqlite3_result_text func(
		arg1 *purego_type_sqlite3_context,
		arg2 string,
		arg3 int32,
		arg4 purego_type_sqlite3_destructor_type,
	)
	purego_func_sqlite3_create_collation func(
		arg1 *purego_type_sqlite3,
		zName string,
		eTextRep int32,
		pArg uintptr, // void *
		xCompare uintptr, // int (*)(void *, int, const void *, int, const void *)
	) int32
	purego_func_sqlite3_create_collation_v2 func(
		arg1 *purego_type_sqlite3,
		zName string,
		eTextRep int32,
		pArg uintptr, // void *
		xCompare uintptr, // int (*)(void *, int, const void *, int, const void *)
		xDestroy purego_type_sqlite3_destructor_type,
	) int32
	purego_func_sqlite3_create_collation16 func(
		arg1 *purego_type_sqlite3,
		zName uintptr, // const void *
		eTextRep int32,
		pArg uintptr, // void *
		xCompare uintptr, // int (*)(void *, int, const void *, int, const void *)
	) int32
	purego_func_sqlite3_commit_hook func(
		arg1 *purego_type_sqlite3,
		arg2 uintptr, // int (*)(void *)
		arg3 uintptr, // void *
	) uintptr // void *
	purego_func_sqlite3_rollback_hook func(
		arg1 *purego_type_sqlite3,
		arg2 purego_type_sqlite3_destructor_type,
		arg3 uintptr, // void *
	) uintptr // void *
	purego_func_sqlite3_update_hook func(
		arg1 *purego_type_sqlite3,
		arg2 uintptr, // void (*)(void *, int, const char *, const char *, sqlite3_int64)
		arg3 uintptr, // void *
	) uintptr // void *
)

func purego_func_sqlite3_bind_blob_bytes(
	arg1 *purego_type_sqlite3_stmt,
	arg2 int32,
	arg3 []byte,
	arg5 purego_type_sqlite3_destructor_type,
) int32 {
	arg3_ptr := uintptr(0)
	arg3_len := arg3
	if len(arg3_len) > 0 {
		arg3_ptr = uintptr(unsafe.Pointer(&arg3_len[0]))
	}
	return purego_func_sqlite3_bind_blob(
		arg1,
		arg2,
		arg3_ptr,
		int32(len(arg3_len)),
		arg5,
	)
}
func purego_func_sqlite3_exec_callbacks(
	arg1 *purego_type_sqlite3,
	sql string,
	callback func(uintptr, int32, uintptr, uintptr) int32,
	arg4 uintptr,
	errmsg uintptr,
) int32 {
	callback_callback := uintptr(0)
	if callback != nil {
		callback_callback = purego.NewCallback(callback)
	}
	return purego_func_sqlite3_exec(
		arg1,
		sql,
		callback_callback,
		arg4,
		errmsg,
	)
}
func purego_func_sqlite3_create_function_callbacks(
	db *purego_type_sqlite3,
	zFunctionName string,
	nArg int32,
	eTextRep int32,
	pApp uintptr,
	xFunc func(*purego_type_sqlite3_context, int32, **purego_type_sqlite3_value),
	xStep func(*purego_type_sqlite3_context, int32, **purego_type_sqlite3_value),
	xFinal func(*purego_type_sqlite3_context),
) int32 {
	xFunc_callback := uintptr(0)
	xStep_callback := uintptr(0)
	xFinal_callback := uintptr(0)
	if xFunc != nil {
		xFunc_callback = purego.NewCallback(xFunc)
	}
	if xStep != nil {
		xStep_callback = purego.NewCallback(xStep)
	}
	if xFinal != nil {
		xFinal_callback = purego.NewCallback(xFinal)
	}
	return purego_func_sqlite3_create_function(
		db,
		zFunctionName,
		nArg,
		eTextRep,
		pApp,
		xFunc_callback,
		xStep_callback,
		xFinal_callback,
	)
}
func purego_func_sqlite3_create_function_v2_callbacks(
	db *purego_type_sqlite3,
	zFunctionName string,
	nArg int32,
	eTextRep int32,
	pApp uintptr,
	xFunc func(*purego_type_sqlite3_context, int32, **purego_type_sqlite3_value),
	xStep func(*purego_type_sqlite3_context, int32, **purego_type_sqlite3_value),
	xFinal func(*purego_type_sqlite3_context),
	xDestroy func(uintptr),
) int32 {
	xFunc_callback := uintptr(0)
	xStep_callback := uintptr(0)
	xFinal_callback := uintptr(0)
	xDestroy_callback := uintptr(0)
	if xFunc != nil {
		xFunc_callback = purego.NewCallback(xFunc)
	}
	if xStep != nil {
		xStep_callback = purego.NewCallback(xStep)
	}
	if xFinal != nil {
		xFinal_callback = purego.NewCallback(xFinal)
	}
	if xDestroy != nil {
		xDestroy_callback = purego.NewCallback(xDestroy)
	}
	return purego_func_sqlite3_create_function_v2(
		db,
		zFunctionName,
		nArg,
		eTextRep,
		pApp,
		xFunc_callback,
		xStep_callback,
		xFinal_callback,
		xDestroy_callback,
	)
}
func purego_func_sqlite3_create_collation_callbacks(
	arg1 *purego_type_sqlite3,
	zName string,
	eTextRep int32,
	pArg uintptr,
	xCompare func(uintptr, int32, uintptr, int32, uintptr) int32,
) int32 {
	xCompare_callback := uintptr(0)
	if xCompare != nil {
		xCompare_callback = purego.NewCallback(xCompare)
	}
	return purego_func_sqlite3_create_collation(
		arg1,
		zName,
		eTextRep,
		pArg,
		xCompare_callback,
	)
}
func purego_func_sqlite3_create_collation_v2_callbacks(
	arg1 *purego_type_sqlite3,
	zName string,
	eTextRep int32,
	pArg uintptr,
	xCompare func(uintptr, int32, uintptr, int32, uintptr) int32,
	xDestroy func(uintptr),
) int32 {
	xCompare_callback := uintptr(0)
	xDestroy_callback := uintptr(0)
	if xCompare != nil {
		xCompare_callback = purego.NewCallback(xCompare)
	}
	if xDestroy != nil {
		xDestroy_callback = purego.NewCallback(xDestroy)
	}
	return purego_func_sqlite3_create_collation_v2(
		arg1,
		zName,
		eTextRep,
		pArg,
		xCompare_callback,
		xDestroy_callback,
	)
}
func purego_func_sqlite3_commit_hook_callbacks(
	arg1 *purego_type_sqlite3,
	arg2 func(uintptr) int32,
	arg3 uintptr,
) uintptr {
	arg2_callback := uintptr(0)
	if arg2 != nil {
		arg2_callback = purego.NewCallback(arg2)
	}
	return purego_func_sqlite3_commit_hook(
		arg1,
		arg2_callback,
		arg3,
	)
}
func purego_func_sqlite3_rollback_hook_callbacks(
	arg1 *purego_type_sqlite3,
	arg2 func(uintptr),
	arg3 uintptr,
) uintptr {
	arg2_callback := uintptr(0)
	if arg2 != nil {
		arg2_callback = purego.NewCallback(arg2)
	}
	return purego_func_sqlite3_rollback_hook(
		arg1,
		arg2_callback,
		arg3,
	)
}
func purego_func_sqlite3_update_hook_callbacks(
	arg1 *purego_type_sqlite3,
	arg2 func(uintptr, int32, uintptr, uintptr, int64),
	arg3 uintptr,
) uintptr {
	arg2_callback := uintptr(0)
	if arg2 != nil {
		arg2_callback = purego.NewCallback(arg2)
	}
	return purego_func_sqlite3_update_hook(
		arg1,
		arg2_callback,
		arg3,
	)
}
func purego_func_sqlite3_progress_handler_callbacks(
	arg1 *purego_type_sqlite3,
	arg2 int32,
	arg3 func(uintptr) int32,
	arg4 uintptr,
) {
	arg3_callback := uintptr(0)
	if arg3 != nil {
		arg3_callback = purego.NewCallback(arg3)
	}
	purego_func_sqlite3_progress_handler(
		arg1,
		arg2,
		arg3_callback,
		arg4,
	)
}
func purego_func_sqlite3_trace_v2_callbacks(
	arg1 *purego_type_sqlite3,
	uMask uint32,
	xCallback func(uint32, uintptr, uintptr, uintptr) int32,
	pCtx uintptr,
) int32 {
	xCallback_callback := uintptr(0)
	if xCallback != nil {
		xCallback_callback = purego.NewCallback(xCallback)
	}
	return purego_func_sqlite3_trace_v2(
		arg1,
		uMask,
		xCallback_callback,
		pCtx,
	)
}

func purego_sqlite3_register_functions(handle uintptr) error {
	purego_func_sqlite3_libversion_symbol, err := purego.Dlsym(handle, "sqlite3_libversion")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_libversion: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_libversion, purego_func_sqlite3_libversion_symbol)
	purego_func_sqlite3_close_symbol, err := purego.Dlsym(handle, "sqlite3_close")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_close: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_close, purego_func_sqlite3_close_symbol)
	purego_func_sqlite3_close_v2_symbol, err := purego.Dlsym(handle, "sqlite3_close_v2")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_close_v2: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_close_v2, purego_func_sqlite3_close_v2_symbol)
	purego_func_sqlite3_exec_symbol, err := purego.Dlsym(handle, "sqlite3_exec")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_exec: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_exec, purego_func_sqlite3_exec_symbol)
	purego_func_sqlite3_last_insert_rowid_symbol, err := purego.Dlsym(handle, "sqlite3_last_insert_rowid")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_last_insert_rowid: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_last_insert_rowid, purego_func_sqlite3_last_insert_rowid_symbol)
	purego_func_sqlite3_changes64_symbol, err := purego.Dlsym(handle, "sqlite3_changes64")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_changes64: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_changes64, purego_func_sqlite3_changes64_symbol)
	purego_func_sqlite3_busy_timeout_symbol, err := purego.Dlsym(handle, "sqlite3_busy_timeout")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_busy_timeout: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_busy_timeout, purego_func_sqlite3_busy_timeout_symbol)
	purego_func_sqlite3_trace_v2_symbol, err := purego.Dlsym(handle, "sqlite3_trace_v2")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_trace_v2: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_trace_v2, purego_func_sqlite3_trace_v2_symbol)
	purego_func_sqlite3_progress_handler_symbol, err := purego.Dlsym(handle, "sqlite3_progress_handler")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_progress_handler: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_progress_handler, purego_func_sqlite3_progress_handler_symbol)
	purego_func_sqlite3_open_symbol, err := purego.Dlsym(handle, "sqlite3_open")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_open: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_open, purego_func_sqlite3_open_symbol)
	purego_func_sqlite3_open_v2_symbol, err := purego.Dlsym(handle, "sqlite3_open_v2")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_open_v2: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_open_v2, purego_func_sqlite3_open_v2_symbol)
	purego_func_sqlite3_extended_errcode_symbol, err := purego.Dlsym(handle, "sqlite3_extended_errcode")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_extended_errcode: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_extended_errcode, purego_func_sqlite3_extended_errcode_symbol)
	purego_func_sqlite3_errmsg_symbol, err := purego.Dlsym(handle, "sqlite3_errmsg")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_errmsg: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_errmsg, purego_func_sqlite3_errmsg_symbol)
	purego_func_sqlite3_prepare_v2_symbol, err := purego.Dlsym(handle, "sqlite3_prepare_v2")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_prepare_v2: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_prepare_v2, purego_func_sqlite3_prepare_v2_symbol)
	purego_func_sqlite3_bind_blob_symbol, err := purego.Dlsym(handle, "sqlite3_bind_blob")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_bind_blob: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_bind_blob, purego_func_sqlite3_bind_blob_symbol)
	purego_func_sqlite3_bind_double_symbol, err := purego.Dlsym(handle, "sqlite3_bind_double")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_bind_double: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_bind_double, purego_func_sqlite3_bind_double_symbol)
	purego_func_sqlite3_bind_int64_symbol, err := purego.Dlsym(handle, "sqlite3_bind_int64")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_bind_int64: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_bind_int64, purego_func_sqlite3_bind_int64_symbol)
	purego_func_sqlite3_bind_null_symbol, err := purego.Dlsym(handle, "sqlite3_bind_null")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_bind_null: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_bind_null, purego_func_sqlite3_bind_null_symbol)
	purego_func_sqlite3_bind_text_symbol, err := purego.Dlsym(handle, "sqlite3_bind_text")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_bind_text: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_bind_text, purego_func_sqlite3_bind_text_symbol)
	purego_func_sqlite3_clear_bindings_symbol, err := purego.Dlsym(handle, "sqlite3_clear_bindings")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_clear_bindings: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_clear_bindings, purego_func_sqlite3_clear_bindings_symbol)
	purego_func_sqlite3_column_count_symbol, err := purego.Dlsym(handle, "sqlite3_column_count")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_column_count: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_column_count, purego_func_sqlite3_column_count_symbol)
	purego_func_sqlite3_step_symbol, err := purego.Dlsym(handle, "sqlite3_step")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_step: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_step, purego_func_sqlite3_step_symbol)
	purego_func_sqlite3_column_blob_symbol, err := purego.Dlsym(handle, "sqlite3_column_blob")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_column_blob: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_column_blob, purego_func_sqlite3_column_blob_symbol)
	purego_func_sqlite3_column_double_symbol, err := purego.Dlsym(handle, "sqlite3_column_double")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_column_double: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_column_double, purego_func_sqlite3_column_double_symbol)
	purego_func_sqlite3_column_int_symbol, err := purego.Dlsym(handle, "sqlite3_column_int")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_column_int: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_column_int, purego_func_sqlite3_column_int_symbol)
	purego_func_sqlite3_column_int64_symbol, err := purego.Dlsym(handle, "sqlite3_column_int64")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_column_int64: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_column_int64, purego_func_sqlite3_column_int64_symbol)
	purego_func_sqlite3_column_text_symbol, err := purego.Dlsym(handle, "sqlite3_column_text")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_column_text: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_column_text, purego_func_sqlite3_column_text_symbol)
	purego_func_sqlite3_column_bytes_symbol, err := purego.Dlsym(handle, "sqlite3_column_bytes")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_column_bytes: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_column_bytes, purego_func_sqlite3_column_bytes_symbol)
	purego_func_sqlite3_column_type_symbol, err := purego.Dlsym(handle, "sqlite3_column_type")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_column_type: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_column_type, purego_func_sqlite3_column_type_symbol)
	purego_func_sqlite3_finalize_symbol, err := purego.Dlsym(handle, "sqlite3_finalize")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_finalize: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_finalize, purego_func_sqlite3_finalize_symbol)
	purego_func_sqlite3_reset_symbol, err := purego.Dlsym(handle, "sqlite3_reset")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_reset: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_reset, purego_func_sqlite3_reset_symbol)
	purego_func_sqlite3_create_function_symbol, err := purego.Dlsym(handle, "sqlite3_create_function")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_create_function: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_create_function, purego_func_sqlite3_create_function_symbol)
	purego_func_sqlite3_create_function16_symbol, err := purego.Dlsym(handle, "sqlite3_create_function16")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_create_function16: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_create_function16, purego_func_sqlite3_create_function16_symbol)
	purego_func_sqlite3_create_function_v2_symbol, err := purego.Dlsym(handle, "sqlite3_create_function_v2")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_create_function_v2: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_create_function_v2, purego_func_sqlite3_create_function_v2_symbol)
	purego_func_sqlite3_value_int_symbol, err := purego.Dlsym(handle, "sqlite3_value_int")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_value_int: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_value_int, purego_func_sqlite3_value_int_symbol)
	purego_func_sqlite3_value_text_symbol, err := purego.Dlsym(handle, "sqlite3_value_text")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_value_text: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_value_text, purego_func_sqlite3_value_text_symbol)
	purego_func_sqlite3_user_data_symbol, err := purego.Dlsym(handle, "sqlite3_user_data")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_user_data: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_user_data, purego_func_sqlite3_user_data_symbol)
	purego_func_sqlite3_result_int_symbol, err := purego.Dlsym(handle, "sqlite3_result_int")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_result_int: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_result_int, purego_func_sqlite3_result_int_symbol)
	purego_func_sqlite3_result_text_symbol, err := purego.Dlsym(handle, "sqlite3_result_text")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_result_text: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_result_text, purego_func_sqlite3_result_text_symbol)
	purego_func_sqlite3_create_collation_symbol, err := purego.Dlsym(handle, "sqlite3_create_collation")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_create_collation: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_create_collation, purego_func_sqlite3_create_collation_symbol)
	purego_func_sqlite3_create_collation_v2_symbol, err := purego.Dlsym(handle, "sqlite3_create_collation_v2")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_create_collation_v2: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_create_collation_v2, purego_func_sqlite3_create_collation_v2_symbol)
	purego_func_sqlite3_create_collation16_symbol, err := purego.Dlsym(handle, "sqlite3_create_collation16")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_create_collation16: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_create_collation16, purego_func_sqlite3_create_collation16_symbol)
	purego_func_sqlite3_commit_hook_symbol, err := purego.Dlsym(handle, "sqlite3_commit_hook")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_commit_hook: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_commit_hook, purego_func_sqlite3_commit_hook_symbol)
	purego_func_sqlite3_rollback_hook_symbol, err := purego.Dlsym(handle, "sqlite3_rollback_hook")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_rollback_hook: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_rollback_hook, purego_func_sqlite3_rollback_hook_symbol)
	purego_func_sqlite3_update_hook_symbol, err := purego.Dlsym(handle, "sqlite3_update_hook")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol sqlite3_update_hook: %w", err)
	}
	purego.RegisterFunc(&purego_func_sqlite3_update_hook, purego_func_sqlite3_update_hook_symbol)
	return nil
}
