// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

type (
	// C: struct fixture_handle
	fixture_handle struct{}
)

var (
	fixture_close func(
		handle *fixture_handle,
	)
)

func fixture_lib_register_functions(handle uintptr) error {
	fixture_close_symbol, err := purego.Dlsym(handle, "fixture_close")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_close: %w", err)
	}
	purego.RegisterFunc(&fixture_close, fixture_close_symbol)
	return nil
}
