// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

type (
	// C: struct fixture_ctx
	fixture_ctx struct{}
)

var (
	fixture_consume func(
		ctx *fixture_ctx,
		// C: const void *
		src uintptr,
		src_size uint64,
	) uint64
)

func fixture_consume_bytes(
	ctx *fixture_ctx,
	src []byte,
) uint64 {
	src_ptr := uintptr(0)
	src_len := src
	if len(src_len) > 0 {
		src_ptr = uintptr(unsafe.Pointer(&src_len[0]))
	}
	return fixture_consume(
		ctx,
		src_ptr,
		uint64(len(src_len)),
	)
}

func fixture_lib_register_functions(handle uintptr) error {
	fixture_consume_symbol, err := purego.Dlsym(handle, "fixture_consume")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_consume: %w", err)
	}
	purego.RegisterFunc(&fixture_consume, fixture_consume_symbol)
	return nil
}
