// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"strings"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

var (
	purego_func_fixture_get_name func(
		id int32,
		// C: const char *
	) uintptr
	purego_func_fixture_free func(
		// C: void *
		ptr uintptr,
	)
)

func purego_func_fixture_get_name_string(
	id int32,
) string {
	rawPtr := purego_func_fixture_get_name(
		id,
	)
	result := purego_gostring(rawPtr)
	if rawPtr != 0 {
		purego_func_fixture_free(rawPtr)
	}
	return result
}

func purego_gostring(ptr uintptr) string {
	if ptr == 0 {
		return ""
	}
	p := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	var n int
	for *(*byte)(unsafe.Add(p, n)) != 0 {
		n++
	}
	return strings.Clone(unsafe.String((*byte)(p), n))
}

func purego_fixture_lib_register_functions(handle uintptr) error {
	purego_func_fixture_get_name_symbol, err := purego.Dlsym(handle, "fixture_get_name")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_get_name: %w", err)
	}
	purego.RegisterFunc(&purego_func_fixture_get_name, purego_func_fixture_get_name_symbol)
	purego_func_fixture_free_symbol, err := purego.Dlsym(handle, "fixture_free")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_free: %w", err)
	}
	purego.RegisterFunc(&purego_func_fixture_free, purego_func_fixture_free_symbol)
	return nil
}
