// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

type (
	// C: fixture_int_inner
	fixture_int_outer = int64
)

var (
	fixture_get func(
		value int64,
	) int64
)

func fixture_lib_register_functions(handle uintptr) error {
	fixture_get_symbol, err := purego.Dlsym(handle, "fixture_get")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_get: %w", err)
	}
	purego.RegisterFunc(&fixture_get, fixture_get_symbol)
	return nil
}
