// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

var (
	fixture_sum_bytes func(
		// C: const void *
		data uintptr,
		data_len uint64,
		salt uint32,
	) int32
)

func fixture_sum_bytes_bytes(
	data []byte,
	salt uint32,
) int32 {
	data_ptr := uintptr(0)
	data_len := data
	if len(data_len) > 0 {
		data_ptr = uintptr(unsafe.Pointer(&data_len[0]))
	}
	return fixture_sum_bytes(
		data_ptr,
		uint64(len(data_len)),
		salt,
	)
}

func fixture_lib_register_functions(handle uintptr) error {
	fixture_sum_bytes_symbol, err := purego.Dlsym(handle, "fixture_sum_bytes")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_sum_bytes: %w", err)
	}
	purego.RegisterFunc(&fixture_sum_bytes, fixture_sum_bytes_symbol)
	return nil
}
