// Code generated by purego-gen; DO NOT EDIT.

package raw

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

type (
	// ! An enum over DuckDB's internal types.
	// C: enum DUCKDB_TYPE
	purego_type_duckdb_type = int32
	// ! An enum over the returned state of different functions.
	// C: enum duckdb_state
	purego_type_duckdb_state = int32
	// ! An enum over DuckDB's different result types.
	// C: enum duckdb_result_type
	purego_type_duckdb_result_type = int32
	// ! An enum over DuckDB's different statement types.
	// C: enum duckdb_statement_type
	purego_type_duckdb_statement_type = int32
	// ! DuckDB's index type.
	// C: uint64_t
	purego_type_idx_t = uint64
	// ! DATE is stored as days since 1970-01-01.
	// ! Use the `duckdb_from_date` and `duckdb_to_date` functions to extract individual information.
	purego_type_duckdb_date = struct {
		days int32
	}
	purego_type_duckdb_date_struct = struct {
		year  int32
		month int8
		day   int8
		_     [2]byte
	}
	// ! TIME is stored as microseconds since 00:00:00.
	// ! Use the `duckdb_from_time` and `duckdb_to_time` functions to extract individual information.
	purego_type_duckdb_time = struct {
		micros int64
	}
	purego_type_duckdb_time_struct = struct {
		hour   int8
		min    int8
		sec    int8
		_      [1]byte
		micros int32
	}
	// ! TIMESTAMP is stored as microseconds since 1970-01-01.
	// ! Use the `duckdb_from_timestamp` and `duckdb_to_timestamp` functions to extract individual information.
	purego_type_duckdb_timestamp = struct {
		micros int64
	}
	purego_type_duckdb_timestamp_struct = struct {
		date struct {
			year  int32
			month int8
			day   int8
			_     [2]byte
		}
		time struct {
			hour   int8
			min    int8
			sec    int8
			_      [1]byte
			micros int32
		}
	}
	// ! INTERVAL is stored in months, days, and micros.
	purego_type_duckdb_interval = struct {
		months int32
		days   int32
		micros int64
	}
	// ! HUGEINT is composed of a lower and upper component.
	// ! Its value is upper * 2^64 + lower.
	// ! For simplified usage, use `duckdb_hugeint_to_double` and `duckdb_double_to_hugeint`.
	purego_type_duckdb_hugeint = struct {
		lower uint64
		upper int64
	}
	// ! DECIMAL is composed of a width and a scale.
	// ! Their value is stored in a HUGEINT.
	purego_type_duckdb_decimal = struct {
		width uint8
		scale uint8
		_     [6]byte
		value struct {
			lower uint64
			upper int64
		}
	}
	// ! A column consists of a pointer to its internal data. Don't operate on this type directly.
	// ! Instead, use functions such as `duckdb_column_data`, `duckdb_nullmask_data`,
	// ! `duckdb_column_type`, and `duckdb_column_name`.
	purego_type_duckdb_column = struct {
		// C: void *
		deprecated_data uintptr
		// C: _Bool *
		deprecated_nullmask uintptr
		deprecated_type     int32
		_                   [4]byte
		// C: char *
		deprecated_name uintptr
		// C: void *
		internal_data uintptr
	}
	// ! 1. A standalone vector that must be destroyed, or
	// ! 2. A vector to a column in a data chunk that lives as long as the data chunk lives.
	// C: struct _duckdb_vector *
	purego_type_duckdb_vector = uintptr
	// ! Strings are composed of a `char` pointer and a size.
	// ! You must free `string.data` with `duckdb_free`.
	purego_type_duckdb_string = struct {
		// C: char *
		data uintptr
		size uint64
	}
	// ! BLOBs are composed of a byte pointer and a size.
	// ! You must free `blob.data` with `duckdb_free`.
	purego_type_duckdb_blob = struct {
		// C: void *
		data uintptr
		size uint64
	}
	// ! A query result consists of a pointer to its internal data.
	// ! Must be freed with 'duckdb_destroy_result'.
	purego_type_duckdb_result = struct {
		deprecated_column_count uint64
		deprecated_row_count    uint64
		deprecated_rows_changed uint64
		// C: duckdb_column *
		deprecated_columns uintptr
		// C: char *
		deprecated_error_message uintptr
		// C: void *
		internal_data uintptr
	}
	// ! A database object. Must be closed with `duckdb_close`.
	// C: struct _duckdb_database *
	purego_type_duckdb_database = uintptr
	// ! A connection to a duckdb database. Must be closed with `duckdb_disconnect`.
	// C: struct _duckdb_connection *
	purego_type_duckdb_connection = uintptr
	// ! A prepared statement is a parameterized query that allows you to bind parameters to it.
	// ! Must be destroyed with `duckdb_destroy_prepare`.
	// C: struct _duckdb_prepared_statement *
	purego_type_duckdb_prepared_statement = uintptr
	// ! The configuration can be used to provide start-up options for a database.
	// ! Must be destroyed with `duckdb_destroy_config`.
	// C: struct _duckdb_config *
	purego_type_duckdb_config = uintptr
	// ! A logical type.
	// ! Must be destroyed with `duckdb_destroy_logical_type`.
	// C: struct _duckdb_logical_type *
	purego_type_duckdb_logical_type = uintptr
	// ! Contains a data chunk of a duckdb_result.
	// ! Must be destroyed with `duckdb_destroy_data_chunk`.
	// C: struct _duckdb_data_chunk *
	purego_type_duckdb_data_chunk = uintptr
)

const (
	DUCKDB_TYPE_INVALID             = 0
	DUCKDB_TYPE_BOOLEAN             = 1
	DUCKDB_TYPE_TINYINT             = 2
	DUCKDB_TYPE_SMALLINT            = 3
	DUCKDB_TYPE_INTEGER             = 4
	DUCKDB_TYPE_BIGINT              = 5
	DUCKDB_TYPE_UTINYINT            = 6
	DUCKDB_TYPE_USMALLINT           = 7
	DUCKDB_TYPE_UINTEGER            = 8
	DUCKDB_TYPE_UBIGINT             = 9
	DUCKDB_TYPE_FLOAT               = 10
	DUCKDB_TYPE_DOUBLE              = 11
	DUCKDB_TYPE_TIMESTAMP           = 12
	DUCKDB_TYPE_DATE                = 13
	DUCKDB_TYPE_TIME                = 14
	DUCKDB_TYPE_INTERVAL            = 15
	DUCKDB_TYPE_HUGEINT             = 16
	DUCKDB_TYPE_UHUGEINT            = 32
	DUCKDB_TYPE_VARCHAR             = 17
	DUCKDB_TYPE_BLOB                = 18
	DUCKDB_TYPE_DECIMAL             = 19
	DUCKDB_TYPE_TIMESTAMP_S         = 20
	DUCKDB_TYPE_TIMESTAMP_MS        = 21
	DUCKDB_TYPE_TIMESTAMP_NS        = 22
	DUCKDB_TYPE_ENUM                = 23
	DUCKDB_TYPE_LIST                = 24
	DUCKDB_TYPE_STRUCT              = 25
	DUCKDB_TYPE_MAP                 = 26
	DUCKDB_TYPE_ARRAY               = 33
	DUCKDB_TYPE_UUID                = 27
	DUCKDB_TYPE_UNION               = 28
	DUCKDB_TYPE_BIT                 = 29
	DUCKDB_TYPE_TIME_TZ             = 30
	DUCKDB_TYPE_TIMESTAMP_TZ        = 31
	DuckDBSuccess                   = 0
	DuckDBError                     = 1
	DUCKDB_RESULT_TYPE_INVALID      = 0
	DUCKDB_RESULT_TYPE_CHANGED_ROWS = 1
	DUCKDB_RESULT_TYPE_NOTHING      = 2
	DUCKDB_RESULT_TYPE_QUERY_RESULT = 3
	DUCKDB_STATEMENT_TYPE_INVALID   = 0
	DUCKDB_STATEMENT_TYPE_SELECT    = 1
	DUCKDB_STATEMENT_TYPE_INSERT    = 2
	DUCKDB_STATEMENT_TYPE_UPDATE    = 3
	DUCKDB_STATEMENT_TYPE_DELETE    = 5
)

var (
	// !
	// Creates a new database or opens an existing database file stored at the given path.
	// If no path is given a new in-memory database is created instead.
	// The database must be closed with 'duckdb_close'.
	//
	// @param path Path to the database file on disk. Both `nullptr` and `:memory:` open an in-memory database.
	// @param out_database The result database object.
	// @return `DuckDBSuccess` on success or `DuckDBError` on failure.
	purego_func_duckdb_open func(
		path string,
		// C: duckdb_database *
		out_database uintptr,
	) int32
	// !
	// Extended version of duckdb_open. Creates a new database or opens an existing database file stored at the given path.
	// The database must be closed with 'duckdb_close'.
	//
	// @param path Path to the database file on disk. Both `nullptr` and `:memory:` open an in-memory database.
	// @param out_database The result database object.
	// @param config (Optional) configuration used to start up the database.
	// @param out_error If set and the function returns `DuckDBError`, this contains the error message.
	// Note that the error message must be freed using `duckdb_free`.
	// @return `DuckDBSuccess` on success or `DuckDBError` on failure.
	purego_func_duckdb_open_ext func(
		path string,
		// C: duckdb_database *
		out_database uintptr,
		// C: duckdb_config
		config uintptr,
		// C: char **
		out_error uintptr,
	) int32
	// !
	// Closes the specified database and de-allocates all memory allocated for that database.
	// This should be called after you are done with any database allocated through `duckdb_open` or `duckdb_open_ext`.
	// Note that failing to call `duckdb_close` (in case of e.g. a program crash) will not cause data corruption.
	// Still, it is recommended to always correctly close a database object after you are done with it.
	//
	// @param database The database object to shut down.
	purego_func_duckdb_close func(
		// C: duckdb_database *
		database uintptr,
	)
	// !
	// Opens a connection to a database. Connections are required to query the database, and store transactional state
	// associated with the connection.
	// The instantiated connection should be closed using 'duckdb_disconnect'.
	//
	// @param database The database file to connect to.
	// @param out_connection The result connection object.
	// @return `DuckDBSuccess` on success or `DuckDBError` on failure.
	purego_func_duckdb_connect func(
		// C: duckdb_database
		database uintptr,
		// C: duckdb_connection *
		out_connection uintptr,
	) int32
	// !
	// Interrupt running query
	//
	// @param connection The connection to interrupt
	purego_func_duckdb_interrupt func(
		// C: duckdb_connection
		connection uintptr,
	)
	// !
	// Closes the specified connection and de-allocates all memory allocated for that connection.
	//
	// @param connection The connection to close.
	purego_func_duckdb_disconnect func(
		// C: duckdb_connection *
		connection uintptr,
	)
	// !
	// Returns the version of the linked DuckDB, with a version postfix for dev versions
	//
	// Usually used for developing C extensions that must return this for a compatibility check.
	purego_func_duckdb_library_version func() string
	// !
	// Initializes an empty configuration object that can be used to provide start-up options for the DuckDB instance
	// through `duckdb_open_ext`.
	// The duckdb_config must be destroyed using 'duckdb_destroy_config'
	//
	// This will always succeed unless there is a malloc failure.
	//
	// Note that `duckdb_destroy_config` should always be called on the resulting config, even if the function returns
	// `DuckDBError`.
	//
	// @param out_config The result configuration object.
	// @return `DuckDBSuccess` on success or `DuckDBError` on failure.
	purego_func_duckdb_create_config func(
		// C: duckdb_config *
		out_config uintptr,
	) int32
	// !
	// Sets the specified option for the specified configuration. The configuration option is indicated by name.
	// To obtain a list of config options, see `duckdb_get_config_flag`.
	//
	// In the source code, configuration options are defined in `config.cpp`.
	//
	// This can fail if either the name is invalid, or if the value provided for the option is invalid.
	//
	// @param config The configuration object to set the option on.
	// @param name The name of the configuration flag to set.
	// @param option The value to set the configuration flag to.
	// @return `DuckDBSuccess` on success or `DuckDBError` on failure.
	purego_func_duckdb_set_config func(
		// C: duckdb_config
		config uintptr,
		name string,
		option string,
	) int32
	// !
	// Destroys the specified configuration object and de-allocates all memory allocated for the object.
	//
	// @param config The configuration object to destroy.
	purego_func_duckdb_destroy_config func(
		// C: duckdb_config *
		config uintptr,
	)
	// !
	// Executes a SQL query within a connection and stores the full (materialized) result in the out_result pointer.
	// If the query fails to execute, DuckDBError is returned and the error message can be retrieved by calling
	// `duckdb_result_error`.
	//
	// Note that after running `duckdb_query`, `duckdb_destroy_result` must be called on the result object even if the
	// query fails, otherwise the error stored within the result will not be freed correctly.
	//
	// @param connection The connection to perform the query in.
	// @param query The SQL query to run.
	// @param out_result The query result.
	// @return `DuckDBSuccess` on success or `DuckDBError` on failure.
	purego_func_duckdb_query func(
		// C: duckdb_connection
		connection uintptr,
		query string,
		// C: duckdb_result *
		out_result uintptr,
	) int32
	// !
	// Closes the result and de-allocates all memory allocated for that result.
	//
	// @param result The result to destroy.
	purego_func_duckdb_destroy_result func(
		// C: duckdb_result *
		result uintptr,
	)
	// !
	// Returns the column name of the specified column. The result should not need to be freed; the column names will
	// automatically be destroyed when the result is destroyed.
	//
	// Returns `NULL` if the column is out of range.
	//
	// @param result The result object to fetch the column name from.
	// @param col The column index.
	// @return The column name of the specified column.
	purego_func_duckdb_column_name func(
		// C: duckdb_result *
		result uintptr,
		col uint64,
	) string
	// !
	// Returns the column type of the specified column.
	//
	// Returns `DUCKDB_TYPE_INVALID` if the column is out of range.
	//
	// @param result The result object to fetch the column type from.
	// @param col The column index.
	// @return The column type of the specified column.
	purego_func_duckdb_column_type func(
		// C: duckdb_result *
		result uintptr,
		col uint64,
	) int32
	// !
	// Returns the logical column type of the specified column.
	//
	// The return type of this call should be destroyed with `duckdb_destroy_logical_type`.
	//
	// Returns `NULL` if the column is out of range.
	//
	// @param result The result object to fetch the column type from.
	// @param col The column index.
	// @return The logical column type of the specified column.
	purego_func_duckdb_column_logical_type func(
		// C: duckdb_result *
		result uintptr,
		col uint64,
		// C: duckdb_logical_type
	) uintptr
	// !
	// Returns the number of columns present in a the result object.
	//
	// @param result The result object.
	// @return The number of columns present in the result object.
	purego_func_duckdb_column_count func(
		// C: duckdb_result *
		result uintptr,
	) uint64
	// !
	// Returns the number of rows changed by the query stored in the result. This is relevant only for INSERT/UPDATE/DELETE
	// queries. For other queries the rows_changed will be 0.
	//
	// @param result The result object.
	// @return The number of rows changed.
	purego_func_duckdb_rows_changed func(
		// C: duckdb_result *
		result uintptr,
	) uint64
	// !
	// Returns the error message contained within the result. The error is only set if `duckdb_query` returns `DuckDBError`.
	//
	// The result of this function must not be freed. It will be cleaned up when `duckdb_destroy_result` is called.
	//
	// @param result The result object to fetch the error from.
	// @return The error of the result.
	purego_func_duckdb_result_error func(
		// C: duckdb_result *
		result uintptr,
	) string
	// !
	// Returns the return_type of the given result, or DUCKDB_RETURN_TYPE_INVALID on error
	//
	// @param result The result object
	// @return The return_type
	purego_func_duckdb_result_return_type func(
		result purego_type_duckdb_result,
	) int32
	// !
	// Allocate `size` bytes of memory using the duckdb internal malloc function. Any memory allocated in this manner
	// should be freed using `duckdb_free`.
	//
	// @param size The number of bytes to allocate.
	// @return A pointer to the allocated memory region.
	purego_func_duckdb_malloc func(
		size uint64,
		// C: void *
	) uintptr
	// !
	// Free a value returned from `duckdb_malloc`, `duckdb_value_varchar`, `duckdb_value_blob`, or
	// `duckdb_value_string`.
	//
	// @param ptr The memory region to de-allocate.
	purego_func_duckdb_free func(
		// C: void *
		ptr uintptr,
	)
	// !
	// The internal vector size used by DuckDB.
	// This is the amount of tuples that will fit into a data chunk created by `duckdb_create_data_chunk`.
	//
	// @return The vector size.
	purego_func_duckdb_vector_size func() uint64
	// !
	// Decompose a `duckdb_date` object into year, month and date (stored as `duckdb_date_struct`).
	//
	// @param date The date object, as obtained from a `DUCKDB_TYPE_DATE` column.
	// @return The `duckdb_date_struct` with the decomposed elements.
	purego_func_duckdb_from_date func(
		date purego_type_duckdb_date,
	) purego_type_duckdb_date_struct
	// !
	// Decompose a `duckdb_time` object into hour, minute, second and microsecond (stored as `duckdb_time_struct`).
	//
	// @param time The time object, as obtained from a `DUCKDB_TYPE_TIME` column.
	// @return The `duckdb_time_struct` with the decomposed elements.
	purego_func_duckdb_from_time func(
		time purego_type_duckdb_time,
	) purego_type_duckdb_time_struct
	// !
	// Decompose a `duckdb_timestamp` object into a `duckdb_timestamp_struct`.
	//
	// @param ts The ts object, as obtained from a `DUCKDB_TYPE_TIMESTAMP` column.
	// @return The `duckdb_timestamp_struct` with the decomposed elements.
	purego_func_duckdb_from_timestamp func(
		ts purego_type_duckdb_timestamp,
	) purego_type_duckdb_timestamp_struct
	// !
	// Create a prepared statement object from a query.
	//
	// Note that after calling `duckdb_prepare`, the prepared statement should always be destroyed using
	// `duckdb_destroy_prepare`, even if the prepare fails.
	//
	// If the prepare fails, `duckdb_prepare_error` can be called to obtain the reason why the prepare failed.
	//
	// @param connection The connection object
	// @param query The SQL query to prepare
	// @param out_prepared_statement The resulting prepared statement object
	// @return `DuckDBSuccess` on success or `DuckDBError` on failure.
	purego_func_duckdb_prepare func(
		// C: duckdb_connection
		connection uintptr,
		query string,
		// C: duckdb_prepared_statement *
		out_prepared_statement uintptr,
	) int32
	// !
	// Closes the prepared statement and de-allocates all memory allocated for the statement.
	//
	// @param prepared_statement The prepared statement to destroy.
	purego_func_duckdb_destroy_prepare func(
		// C: duckdb_prepared_statement *
		prepared_statement uintptr,
	)
	// !
	// Returns the error message associated with the given prepared statement.
	// If the prepared statement has no error message, this returns `nullptr` instead.
	//
	// The error message should not be freed. It will be de-allocated when `duckdb_destroy_prepare` is called.
	//
	// @param prepared_statement The prepared statement to obtain the error from.
	// @return The error message, or `nullptr` if there is none.
	purego_func_duckdb_prepare_error func(
		// C: duckdb_prepared_statement
		prepared_statement uintptr,
	) string
	// !
	// Returns the number of parameters that can be provided to the given prepared statement.
	//
	// Returns 0 if the query was not successfully prepared.
	//
	// @param prepared_statement The prepared statement to obtain the number of parameters for.
	purego_func_duckdb_nparams func(
		// C: duckdb_prepared_statement
		prepared_statement uintptr,
	) uint64
	// !
	// Returns the name used to identify the parameter
	// The returned string should be freed using `duckdb_free`.
	//
	// Returns NULL if the index is out of range for the provided prepared statement.
	//
	// @param prepared_statement The prepared statement for which to get the parameter name from.
	purego_func_duckdb_parameter_name func(
		// C: duckdb_prepared_statement
		prepared_statement uintptr,
		index uint64,
	) string
	// !
	// Clear the params bind to the prepared statement.
	purego_func_duckdb_clear_bindings func(
		// C: duckdb_prepared_statement
		prepared_statement uintptr,
	) int32
	// !
	// Returns the statement type of the statement to be executed
	//
	// @param statement The prepared statement.
	// @return duckdb_statement_type value or DUCKDB_STATEMENT_TYPE_INVALID
	purego_func_duckdb_prepared_statement_type func(
		// C: duckdb_prepared_statement
		statement uintptr,
	) int32
	// !
	// Retrieve the index of the parameter for the prepared statement, identified by name
	purego_func_duckdb_bind_parameter_index func(
		// C: duckdb_prepared_statement
		prepared_statement uintptr,
		// C: idx_t *
		param_idx_out uintptr,
		name string,
	) int32
	// !
	// Binds a bool value to the prepared statement at the specified index.
	purego_func_duckdb_bind_boolean func(
		// C: duckdb_prepared_statement
		prepared_statement uintptr,
		param_idx uint64,
		val bool,
	) int32
	// !
	// Binds an int32_t value to the prepared statement at the specified index.
	purego_func_duckdb_bind_int32 func(
		// C: duckdb_prepared_statement
		prepared_statement uintptr,
		param_idx uint64,
		val int32,
	) int32
	// !
	// Binds an int64_t value to the prepared statement at the specified index.
	purego_func_duckdb_bind_int64 func(
		// C: duckdb_prepared_statement
		prepared_statement uintptr,
		param_idx uint64,
		val int64,
	) int32
	// !
	// Binds a float value to the prepared statement at the specified index.
	purego_func_duckdb_bind_float func(
		// C: duckdb_prepared_statement
		prepared_statement uintptr,
		param_idx uint64,
		val float32,
	) int32
	// !
	// Binds a double value to the prepared statement at the specified index.
	purego_func_duckdb_bind_double func(
		// C: duckdb_prepared_statement
		prepared_statement uintptr,
		param_idx uint64,
		val float64,
	) int32
	// !
	// Binds a duckdb_timestamp value to the prepared statement at the specified index.
	purego_func_duckdb_bind_timestamp func(
		// C: duckdb_prepared_statement
		prepared_statement uintptr,
		param_idx uint64,
		val purego_type_duckdb_timestamp,
	) int32
	// !
	// Binds a null-terminated varchar value to the prepared statement at the specified index.
	//
	// Superseded by `duckdb_bind_value`.
	purego_func_duckdb_bind_varchar func(
		// C: duckdb_prepared_statement
		prepared_statement uintptr,
		param_idx uint64,
		val string,
	) int32
	// !
	// Binds a varchar value to the prepared statement at the specified index.
	//
	// Superseded by `duckdb_bind_value`.
	purego_func_duckdb_bind_varchar_length func(
		// C: duckdb_prepared_statement
		prepared_statement uintptr,
		param_idx uint64,
		val string,
		length uint64,
	) int32
	// !
	// Binds a blob value to the prepared statement at the specified index.
	purego_func_duckdb_bind_blob func(
		// C: duckdb_prepared_statement
		prepared_statement uintptr,
		param_idx uint64,
		// C: const void *
		data uintptr,
		length uint64,
	) int32
	// !
	// Binds a NULL value to the prepared statement at the specified index.
	purego_func_duckdb_bind_null func(
		// C: duckdb_prepared_statement
		prepared_statement uintptr,
		param_idx uint64,
	) int32
	// !
	// Executes the prepared statement with the given bound parameters, and returns a materialized query result.
	//
	// This method can be called multiple times for each prepared statement, and the parameters can be modified
	// between calls to this function.
	//
	// Note that the result must be freed with `duckdb_destroy_result`.
	//
	// @param prepared_statement The prepared statement to execute.
	// @param out_result The query result.
	// @return `DuckDBSuccess` on success or `DuckDBError` on failure.
	purego_func_duckdb_execute_prepared func(
		// C: duckdb_prepared_statement
		prepared_statement uintptr,
		// C: duckdb_result *
		out_result uintptr,
	) int32
	// !
	// Retrieves the enum `duckdb_type` of a `duckdb_logical_type`.
	//
	// @param type The logical type.
	// @return The `duckdb_type` id.
	purego_func_duckdb_get_type_id func(
		// C: duckdb_logical_type
		type_ uintptr,
	) int32
	// !
	// Retrieves the width of a decimal type.
	//
	// @param type The logical type object
	// @return The width of the decimal type
	purego_func_duckdb_decimal_width func(
		// C: duckdb_logical_type
		type_ uintptr,
	) uint8
	// !
	// Retrieves the scale of a decimal type.
	//
	// @param type The logical type object
	// @return The scale of the decimal type
	purego_func_duckdb_decimal_scale func(
		// C: duckdb_logical_type
		type_ uintptr,
	) uint8
	// !
	// Destroys the logical type and de-allocates all memory allocated for that type.
	//
	// @param type The logical type to destroy.
	purego_func_duckdb_destroy_logical_type func(
		// C: duckdb_logical_type *
		type_ uintptr,
	)
	// !
	// Destroys the data chunk and de-allocates all memory allocated for that chunk.
	//
	// @param chunk The data chunk to destroy.
	purego_func_duckdb_destroy_data_chunk func(
		// C: duckdb_data_chunk *
		chunk uintptr,
	)
	// !
	// Retrieves the number of columns in a data chunk.
	//
	// @param chunk The data chunk to get the data from
	// @return The number of columns in the data chunk
	purego_func_duckdb_data_chunk_get_column_count func(
		// C: duckdb_data_chunk
		chunk uintptr,
	) uint64
	// !
	// Retrieves the vector at the specified column index in the data chunk.
	//
	// The pointer to the vector is valid for as long as the chunk is alive.
	// It does NOT need to be destroyed.
	//
	// @param chunk The data chunk to get the data from
	// @return The vector
	purego_func_duckdb_data_chunk_get_vector func(
		// C: duckdb_data_chunk
		chunk uintptr,
		col_idx uint64,
		// C: duckdb_vector
	) uintptr
	// !
	// Retrieves the current number of tuples in a data chunk.
	//
	// @param chunk The data chunk to get the data from
	// @return The number of tuples in the data chunk
	purego_func_duckdb_data_chunk_get_size func(
		// C: duckdb_data_chunk
		chunk uintptr,
	) uint64
	// !
	// Retrieves the column type of the specified vector.
	//
	// The result must be destroyed with `duckdb_destroy_logical_type`.
	//
	// @param vector The vector get the data from
	// @return The type of the vector
	purego_func_duckdb_vector_get_column_type func(
		// C: duckdb_vector
		vector uintptr,
		// C: duckdb_logical_type
	) uintptr
	// !
	// Retrieves the data pointer of the vector.
	//
	// The data pointer can be used to read or write values from the vector.
	// How to read or write values depends on the type of the vector.
	//
	// @param vector The vector to get the data from
	// @return The data pointer
	purego_func_duckdb_vector_get_data func(
		// C: duckdb_vector
		vector uintptr,
		// C: void *
	) uintptr
	// !
	// Retrieves the validity mask pointer of the specified vector.
	//
	// If all values are valid, this function MIGHT return NULL!
	//
	// The validity mask is a bitset that signifies null-ness within the data chunk.
	// It is a series of uint64_t values, where each uint64_t value contains validity for 64 tuples.
	// The bit is set to 1 if the value is valid (i.e. not NULL) or 0 if the value is invalid (i.e. NULL).
	//
	// Validity of a specific value can be obtained like this:
	//
	// idx_t entry_idx = row_idx / 64;
	// idx_t idx_in_entry = row_idx % 64;
	// bool is_valid = validity_mask[entry_idx] & (1 << idx_in_entry);
	//
	// Alternatively, the (slower) duckdb_validity_row_is_valid function can be used.
	//
	// @param vector The vector to get the data from
	// @return The pointer to the validity mask, or NULL if no validity mask is present
	purego_func_duckdb_vector_get_validity func(
		// C: duckdb_vector
		vector uintptr,
		// C: uint64_t *
	) uintptr
	// !
	// Returns whether or not a row is valid (i.e. not NULL) in the given validity mask.
	//
	// @param validity The validity mask, as obtained through `duckdb_vector_get_validity`
	// @param row The row index
	// @return true if the row is valid, false otherwise
	purego_func_duckdb_validity_row_is_valid func(
		// C: uint64_t *
		validity uintptr,
		row uint64,
	) bool
	// !
	// Fetches a data chunk from a duckdb_result. This function should be called repeatedly until the result is exhausted.
	//
	// The result must be destroyed with `duckdb_destroy_data_chunk`.
	//
	// It is not known beforehand how many chunks will be returned by this result.
	//
	// @param result The result object to fetch the data chunk from.
	// @return The resulting data chunk. Returns `NULL` if the result has an error.
	purego_func_duckdb_fetch_chunk func(
		result purego_type_duckdb_result,
		// C: duckdb_data_chunk
	) uintptr
)

func purego_duckdb_register_functions(handle uintptr) error {
	purego_func_duckdb_open_symbol, err := purego.Dlsym(handle, "duckdb_open")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_open: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_open, purego_func_duckdb_open_symbol)
	purego_func_duckdb_open_ext_symbol, err := purego.Dlsym(handle, "duckdb_open_ext")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_open_ext: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_open_ext, purego_func_duckdb_open_ext_symbol)
	purego_func_duckdb_close_symbol, err := purego.Dlsym(handle, "duckdb_close")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_close: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_close, purego_func_duckdb_close_symbol)
	purego_func_duckdb_connect_symbol, err := purego.Dlsym(handle, "duckdb_connect")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_connect: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_connect, purego_func_duckdb_connect_symbol)
	purego_func_duckdb_interrupt_symbol, err := purego.Dlsym(handle, "duckdb_interrupt")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_interrupt: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_interrupt, purego_func_duckdb_interrupt_symbol)
	purego_func_duckdb_disconnect_symbol, err := purego.Dlsym(handle, "duckdb_disconnect")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_disconnect: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_disconnect, purego_func_duckdb_disconnect_symbol)
	purego_func_duckdb_library_version_symbol, err := purego.Dlsym(handle, "duckdb_library_version")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_library_version: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_library_version, purego_func_duckdb_library_version_symbol)
	purego_func_duckdb_create_config_symbol, err := purego.Dlsym(handle, "duckdb_create_config")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_create_config: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_create_config, purego_func_duckdb_create_config_symbol)
	purego_func_duckdb_set_config_symbol, err := purego.Dlsym(handle, "duckdb_set_config")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_set_config: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_set_config, purego_func_duckdb_set_config_symbol)
	purego_func_duckdb_destroy_config_symbol, err := purego.Dlsym(handle, "duckdb_destroy_config")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_destroy_config: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_destroy_config, purego_func_duckdb_destroy_config_symbol)
	purego_func_duckdb_query_symbol, err := purego.Dlsym(handle, "duckdb_query")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_query: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_query, purego_func_duckdb_query_symbol)
	purego_func_duckdb_destroy_result_symbol, err := purego.Dlsym(handle, "duckdb_destroy_result")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_destroy_result: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_destroy_result, purego_func_duckdb_destroy_result_symbol)
	purego_func_duckdb_column_name_symbol, err := purego.Dlsym(handle, "duckdb_column_name")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_column_name: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_column_name, purego_func_duckdb_column_name_symbol)
	purego_func_duckdb_column_type_symbol, err := purego.Dlsym(handle, "duckdb_column_type")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_column_type: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_column_type, purego_func_duckdb_column_type_symbol)
	purego_func_duckdb_column_logical_type_symbol, err := purego.Dlsym(handle, "duckdb_column_logical_type")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_column_logical_type: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_column_logical_type, purego_func_duckdb_column_logical_type_symbol)
	purego_func_duckdb_column_count_symbol, err := purego.Dlsym(handle, "duckdb_column_count")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_column_count: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_column_count, purego_func_duckdb_column_count_symbol)
	purego_func_duckdb_rows_changed_symbol, err := purego.Dlsym(handle, "duckdb_rows_changed")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_rows_changed: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_rows_changed, purego_func_duckdb_rows_changed_symbol)
	purego_func_duckdb_result_error_symbol, err := purego.Dlsym(handle, "duckdb_result_error")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_result_error: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_result_error, purego_func_duckdb_result_error_symbol)
	purego_func_duckdb_result_return_type_symbol, err := purego.Dlsym(handle, "duckdb_result_return_type")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_result_return_type: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_result_return_type, purego_func_duckdb_result_return_type_symbol)
	purego_func_duckdb_malloc_symbol, err := purego.Dlsym(handle, "duckdb_malloc")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_malloc: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_malloc, purego_func_duckdb_malloc_symbol)
	purego_func_duckdb_free_symbol, err := purego.Dlsym(handle, "duckdb_free")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_free: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_free, purego_func_duckdb_free_symbol)
	purego_func_duckdb_vector_size_symbol, err := purego.Dlsym(handle, "duckdb_vector_size")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_vector_size: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_vector_size, purego_func_duckdb_vector_size_symbol)
	purego_func_duckdb_from_date_symbol, err := purego.Dlsym(handle, "duckdb_from_date")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_from_date: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_from_date, purego_func_duckdb_from_date_symbol)
	purego_func_duckdb_from_time_symbol, err := purego.Dlsym(handle, "duckdb_from_time")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_from_time: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_from_time, purego_func_duckdb_from_time_symbol)
	purego_func_duckdb_from_timestamp_symbol, err := purego.Dlsym(handle, "duckdb_from_timestamp")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_from_timestamp: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_from_timestamp, purego_func_duckdb_from_timestamp_symbol)
	purego_func_duckdb_prepare_symbol, err := purego.Dlsym(handle, "duckdb_prepare")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_prepare: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_prepare, purego_func_duckdb_prepare_symbol)
	purego_func_duckdb_destroy_prepare_symbol, err := purego.Dlsym(handle, "duckdb_destroy_prepare")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_destroy_prepare: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_destroy_prepare, purego_func_duckdb_destroy_prepare_symbol)
	purego_func_duckdb_prepare_error_symbol, err := purego.Dlsym(handle, "duckdb_prepare_error")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_prepare_error: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_prepare_error, purego_func_duckdb_prepare_error_symbol)
	purego_func_duckdb_nparams_symbol, err := purego.Dlsym(handle, "duckdb_nparams")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_nparams: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_nparams, purego_func_duckdb_nparams_symbol)
	purego_func_duckdb_parameter_name_symbol, err := purego.Dlsym(handle, "duckdb_parameter_name")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_parameter_name: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_parameter_name, purego_func_duckdb_parameter_name_symbol)
	purego_func_duckdb_clear_bindings_symbol, err := purego.Dlsym(handle, "duckdb_clear_bindings")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_clear_bindings: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_clear_bindings, purego_func_duckdb_clear_bindings_symbol)
	purego_func_duckdb_prepared_statement_type_symbol, err := purego.Dlsym(handle, "duckdb_prepared_statement_type")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_prepared_statement_type: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_prepared_statement_type, purego_func_duckdb_prepared_statement_type_symbol)
	purego_func_duckdb_bind_parameter_index_symbol, err := purego.Dlsym(handle, "duckdb_bind_parameter_index")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_bind_parameter_index: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_bind_parameter_index, purego_func_duckdb_bind_parameter_index_symbol)
	purego_func_duckdb_bind_boolean_symbol, err := purego.Dlsym(handle, "duckdb_bind_boolean")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_bind_boolean: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_bind_boolean, purego_func_duckdb_bind_boolean_symbol)
	purego_func_duckdb_bind_int32_symbol, err := purego.Dlsym(handle, "duckdb_bind_int32")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_bind_int32: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_bind_int32, purego_func_duckdb_bind_int32_symbol)
	purego_func_duckdb_bind_int64_symbol, err := purego.Dlsym(handle, "duckdb_bind_int64")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_bind_int64: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_bind_int64, purego_func_duckdb_bind_int64_symbol)
	purego_func_duckdb_bind_float_symbol, err := purego.Dlsym(handle, "duckdb_bind_float")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_bind_float: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_bind_float, purego_func_duckdb_bind_float_symbol)
	purego_func_duckdb_bind_double_symbol, err := purego.Dlsym(handle, "duckdb_bind_double")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_bind_double: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_bind_double, purego_func_duckdb_bind_double_symbol)
	purego_func_duckdb_bind_timestamp_symbol, err := purego.Dlsym(handle, "duckdb_bind_timestamp")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_bind_timestamp: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_bind_timestamp, purego_func_duckdb_bind_timestamp_symbol)
	purego_func_duckdb_bind_varchar_symbol, err := purego.Dlsym(handle, "duckdb_bind_varchar")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_bind_varchar: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_bind_varchar, purego_func_duckdb_bind_varchar_symbol)
	purego_func_duckdb_bind_varchar_length_symbol, err := purego.Dlsym(handle, "duckdb_bind_varchar_length")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_bind_varchar_length: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_bind_varchar_length, purego_func_duckdb_bind_varchar_length_symbol)
	purego_func_duckdb_bind_blob_symbol, err := purego.Dlsym(handle, "duckdb_bind_blob")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_bind_blob: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_bind_blob, purego_func_duckdb_bind_blob_symbol)
	purego_func_duckdb_bind_null_symbol, err := purego.Dlsym(handle, "duckdb_bind_null")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_bind_null: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_bind_null, purego_func_duckdb_bind_null_symbol)
	purego_func_duckdb_execute_prepared_symbol, err := purego.Dlsym(handle, "duckdb_execute_prepared")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_execute_prepared: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_execute_prepared, purego_func_duckdb_execute_prepared_symbol)
	purego_func_duckdb_get_type_id_symbol, err := purego.Dlsym(handle, "duckdb_get_type_id")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_get_type_id: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_get_type_id, purego_func_duckdb_get_type_id_symbol)
	purego_func_duckdb_decimal_width_symbol, err := purego.Dlsym(handle, "duckdb_decimal_width")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_decimal_width: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_decimal_width, purego_func_duckdb_decimal_width_symbol)
	purego_func_duckdb_decimal_scale_symbol, err := purego.Dlsym(handle, "duckdb_decimal_scale")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_decimal_scale: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_decimal_scale, purego_func_duckdb_decimal_scale_symbol)
	purego_func_duckdb_destroy_logical_type_symbol, err := purego.Dlsym(handle, "duckdb_destroy_logical_type")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_destroy_logical_type: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_destroy_logical_type, purego_func_duckdb_destroy_logical_type_symbol)
	purego_func_duckdb_destroy_data_chunk_symbol, err := purego.Dlsym(handle, "duckdb_destroy_data_chunk")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_destroy_data_chunk: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_destroy_data_chunk, purego_func_duckdb_destroy_data_chunk_symbol)
	purego_func_duckdb_data_chunk_get_column_count_symbol, err := purego.Dlsym(handle, "duckdb_data_chunk_get_column_count")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_data_chunk_get_column_count: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_data_chunk_get_column_count, purego_func_duckdb_data_chunk_get_column_count_symbol)
	purego_func_duckdb_data_chunk_get_vector_symbol, err := purego.Dlsym(handle, "duckdb_data_chunk_get_vector")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_data_chunk_get_vector: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_data_chunk_get_vector, purego_func_duckdb_data_chunk_get_vector_symbol)
	purego_func_duckdb_data_chunk_get_size_symbol, err := purego.Dlsym(handle, "duckdb_data_chunk_get_size")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_data_chunk_get_size: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_data_chunk_get_size, purego_func_duckdb_data_chunk_get_size_symbol)
	purego_func_duckdb_vector_get_column_type_symbol, err := purego.Dlsym(handle, "duckdb_vector_get_column_type")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_vector_get_column_type: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_vector_get_column_type, purego_func_duckdb_vector_get_column_type_symbol)
	purego_func_duckdb_vector_get_data_symbol, err := purego.Dlsym(handle, "duckdb_vector_get_data")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_vector_get_data: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_vector_get_data, purego_func_duckdb_vector_get_data_symbol)
	purego_func_duckdb_vector_get_validity_symbol, err := purego.Dlsym(handle, "duckdb_vector_get_validity")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_vector_get_validity: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_vector_get_validity, purego_func_duckdb_vector_get_validity_symbol)
	purego_func_duckdb_validity_row_is_valid_symbol, err := purego.Dlsym(handle, "duckdb_validity_row_is_valid")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_validity_row_is_valid: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_validity_row_is_valid, purego_func_duckdb_validity_row_is_valid_symbol)
	purego_func_duckdb_fetch_chunk_symbol, err := purego.Dlsym(handle, "duckdb_fetch_chunk")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol duckdb_fetch_chunk: %w", err)
	}
	purego.RegisterFunc(&purego_func_duckdb_fetch_chunk, purego_func_duckdb_fetch_chunk_symbol)
	return nil
}
