// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

type (
	// C: void (*)(void *)
	purego_type_fixture_destructor_t = uintptr
	// C: void (*)(void *)
	purego_type_fixture_destructor_t_func = func(uintptr)
)

func purego_new_fixture_destructor_t(fn purego_type_fixture_destructor_t_func) purego_type_fixture_destructor_t {
	return purego_type_fixture_destructor_t(purego.NewCallback(fn))
}

const (
	purego_const_FIXTURE_STATIC    purego_type_fixture_destructor_t = 0
	purego_const_FIXTURE_TRANSIENT purego_type_fixture_destructor_t = ^uintptr(0)
)
