// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

type (
	// Doxygen typedef comment.
	// C: int
	fixture_doc_type_t = int32
	// C: int
	fixture_plain_type_t = int32
)

const (
	// Doxygen enum constant comment.
	FIXTURE_DOC_STATUS   = 1
	FIXTURE_PLAIN_STATUS = 2
)

var (
	// Doxygen function comment.
	fixture_doc_add func(
		lhs int32,
		rhs int32,
	) int32
	fixture_plain_add func(
		lhs int32,
		rhs int32,
	) int32
)

func fixture_lib_register_functions(handle uintptr) error {
	fixture_doc_add_symbol, err := purego.Dlsym(handle, "fixture_doc_add")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_doc_add: %w", err)
	}
	purego.RegisterFunc(&fixture_doc_add, fixture_doc_add_symbol)
	fixture_plain_add_symbol, err := purego.Dlsym(handle, "fixture_plain_add")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_plain_add: %w", err)
	}
	purego.RegisterFunc(&fixture_plain_add, fixture_plain_add_symbol)
	return nil
}

var (
	// Doxygen runtime-var comment.
	fixture_doc_counter   uintptr
	fixture_plain_counter uintptr
)

func fixture_lib_load_runtime_vars(handle uintptr) error {
	fixture_doc_counter_symbol, err := purego.Dlsym(handle, "fixture_doc_counter")
	if err != nil {
		return fmt.Errorf(
			"purego-gen: failed to resolve runtime var symbol fixture_doc_counter: %w",
			err,
		)
	}
	fixture_doc_counter = fixture_doc_counter_symbol
	fixture_plain_counter_symbol, err := purego.Dlsym(handle, "fixture_plain_counter")
	if err != nil {
		return fmt.Errorf(
			"purego-gen: failed to resolve runtime var symbol fixture_plain_counter: %w",
			err,
		)
	}
	fixture_plain_counter = fixture_plain_counter_symbol
	return nil
}
