// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

var (
	fixture_set_handler func(
		on_ready func(int32, uintptr),
		// C: void *
		user_data uintptr,
	)
	fixture_transform func(
		fn func(int32) int32,
		value int32,
	) int32
)

func fixture_lib_register_functions(handle uintptr) error {
	fixture_set_handler_symbol, err := purego.Dlsym(handle, "fixture_set_handler")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_set_handler: %w", err)
	}
	purego.RegisterFunc(&fixture_set_handler, fixture_set_handler_symbol)
	fixture_transform_symbol, err := purego.Dlsym(handle, "fixture_transform")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_transform: %w", err)
	}
	purego.RegisterFunc(&fixture_transform, fixture_transform_symbol)
	return nil
}
