// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

var (
	fixture_pointer_to_int_param func(
		out *int32,
	)
)

func fixture_lib_register_functions(handle uintptr) error {
	fixture_pointer_to_int_param_symbol, err := purego.Dlsym(handle, "fixture_pointer_to_int_param")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_pointer_to_int_param: %w", err)
	}
	purego.RegisterFunc(&fixture_pointer_to_int_param, fixture_pointer_to_int_param_symbol)
	return nil
}
