// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"

	"github.com/ebitengine/purego"
)

type (
	purego_type_my_int    = int32
	purego_type_my_handle = uintptr
)

var (
	purego_func_add func(
		int32,
		int32,
	) int32
	purego_func_reset func()
)

func purego_fixture_lib_register_functions(handle uintptr) error {
	purego_func_add_symbol, err := purego.Dlsym(handle, "add")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol add: %w", err)
	}
	purego.RegisterFunc(&purego_func_add, purego_func_add_symbol)
	purego_func_reset_symbol, err := purego.Dlsym(handle, "reset")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol reset: %w", err)
	}
	purego.RegisterFunc(&purego_func_reset, purego_func_reset_symbol)
	return nil
}
