// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
)

var (
	purego_func_smoke_const_greeting    func() string
	purego_func_smoke_const_is_expected func(
		string,
	) int32
	purego_func_smoke_const_roundtrip func(
		string,
	) string
)

func purego_fixture_lib_register_functions(handle uintptr) error {
	purego_func_smoke_const_greeting_symbol, err := purego.Dlsym(handle, "smoke_const_greeting")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol smoke_const_greeting: %w", err)
	}
	purego.RegisterFunc(&purego_func_smoke_const_greeting, purego_func_smoke_const_greeting_symbol)
	purego_func_smoke_const_is_expected_symbol, err := purego.Dlsym(handle, "smoke_const_is_expected")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol smoke_const_is_expected: %w", err)
	}
	purego.RegisterFunc(&purego_func_smoke_const_is_expected, purego_func_smoke_const_is_expected_symbol)
	purego_func_smoke_const_roundtrip_symbol, err := purego.Dlsym(handle, "smoke_const_roundtrip")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol smoke_const_roundtrip: %w", err)
	}
	purego.RegisterFunc(&purego_func_smoke_const_roundtrip, purego_func_smoke_const_roundtrip_symbol)
	return nil
}
