// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

const (
	FIXTURE_STATUS_OK = 0
)

var (
	add func(
		lhs int32,
		rhs int32,
	) int32
)

func fixture_lib_register_functions(handle uintptr) error {
	add_symbol, err := purego.Dlsym(handle, "add")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol add: %w", err)
	}
	purego.RegisterFunc(&add, add_symbol)
	return nil
}

var (
	build_id uintptr
)

func fixture_lib_load_runtime_vars(handle uintptr) error {
	build_id_symbol, err := purego.Dlsym(handle, "build_id")
	if err != nil {
		return fmt.Errorf(
			"purego-gen: failed to resolve runtime var symbol build_id: %w",
			err,
		)
	}
	build_id = build_id_symbol
	return nil
}
