// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

var (
	base_add func(
		lhs int32,
		rhs int32,
	) int32
)

func fixture_lib_register_functions(handle uintptr) error {
	base_add_symbol, err := purego.Dlsym(handle, "base_add")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol base_add: %w", err)
	}
	purego.RegisterFunc(&base_add, base_add_symbol)
	return nil
}
