// Code generated by purego-gen; DO NOT EDIT.

package fixture

type (
	// C: int
	purego_type_my_int = int32
	// C: void *
	purego_type_my_handle = uintptr
	// C: struct not_basic
	purego_type_not_basic struct{}
)
