// Code generated by purego-gen; DO NOT EDIT.

package fixture

type (
	purego_type_my_int    = int32   // int
	purego_type_my_handle = uintptr // void *
	purego_type_not_basic uintptr   // struct not_basic
)
