// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

var (
	lib_send_data func(
		fd int32,
		// C: const void *
		data uintptr,
		data_len uint64,
	) int32
	lib_write_blob func(
		// C: const void *
		buf uintptr,
		buf_len uint32,
		flags uint32,
	) int32
	lib_get_count func(
		id int32,
	) int32
	lib_read_str func(
		str string,
		str_len uint64,
	) int32
)

func lib_send_data_bytes(
	fd int32,
	data []byte,
) int32 {
	data_ptr := uintptr(0)
	data_len := data
	if len(data_len) > 0 {
		data_ptr = uintptr(unsafe.Pointer(&data_len[0]))
	}
	return lib_send_data(
		fd,
		data_ptr,
		uint64(len(data_len)),
	)
}
func lib_write_blob_bytes(
	buf []byte,
	flags uint32,
) int32 {
	buf_ptr := uintptr(0)
	buf_len := buf
	if len(buf_len) > 0 {
		buf_ptr = uintptr(unsafe.Pointer(&buf_len[0]))
	}
	return lib_write_blob(
		buf_ptr,
		uint32(len(buf_len)),
		flags,
	)
}

func fixture_lib_register_functions(handle uintptr) error {
	lib_send_data_symbol, err := purego.Dlsym(handle, "lib_send_data")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol lib_send_data: %w", err)
	}
	purego.RegisterFunc(&lib_send_data, lib_send_data_symbol)
	lib_write_blob_symbol, err := purego.Dlsym(handle, "lib_write_blob")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol lib_write_blob: %w", err)
	}
	purego.RegisterFunc(&lib_write_blob, lib_write_blob_symbol)
	lib_get_count_symbol, err := purego.Dlsym(handle, "lib_get_count")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol lib_get_count: %w", err)
	}
	purego.RegisterFunc(&lib_get_count, lib_get_count_symbol)
	lib_read_str_symbol, err := purego.Dlsym(handle, "lib_read_str")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol lib_read_str: %w", err)
	}
	purego.RegisterFunc(&lib_read_str, lib_read_str_symbol)
	return nil
}
