// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

var (
	smoke_reset       func() int32
	smoke_increment   func() int32
	smoke_get_counter func() int32
)

func fixture_lib_register_functions(handle uintptr) error {
	smoke_reset_symbol, err := purego.Dlsym(handle, "smoke_reset")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol smoke_reset: %w", err)
	}
	purego.RegisterFunc(&smoke_reset, smoke_reset_symbol)
	smoke_increment_symbol, err := purego.Dlsym(handle, "smoke_increment")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol smoke_increment: %w", err)
	}
	purego.RegisterFunc(&smoke_increment, smoke_increment_symbol)
	smoke_get_counter_symbol, err := purego.Dlsym(handle, "smoke_get_counter")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol smoke_get_counter: %w", err)
	}
	purego.RegisterFunc(&smoke_get_counter, smoke_get_counter_symbol)
	return nil
}

var (
	smoke_magic uintptr
	smoke_epoch uintptr
)

func fixture_lib_load_runtime_vars(handle uintptr) error {
	smoke_magic_symbol, err := purego.Dlsym(handle, "smoke_magic")
	if err != nil {
		return fmt.Errorf(
			"purego-gen: failed to resolve runtime var symbol smoke_magic: %w",
			err,
		)
	}
	smoke_magic = smoke_magic_symbol
	smoke_epoch_symbol, err := purego.Dlsym(handle, "smoke_epoch")
	if err != nil {
		return fmt.Errorf(
			"purego-gen: failed to resolve runtime var symbol smoke_epoch: %w",
			err,
		)
	}
	smoke_epoch = smoke_epoch_symbol
	return nil
}
