// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
)

type (
	// An "index" that consists of a set of translation units that would
	// typically be linked together into an executable or library.
	purego_type_CXIndex = uintptr
	// A single translation unit, which resides in an index.
	purego_type_CXTranslationUnit = uintptr
)

var (
	// Provides a shared context for creating translation units.
	//
	// It provides two options:
	//
	// - excludeDeclarationsFromPCH: When non-zero, allows enumeration of "local"
	// declarations (when loading any new translation units). A "local" declaration
	// is one that belongs in the translation unit itself and not in a precompiled
	// header that was used by the translation unit. If zero, all declarations
	// will be enumerated.
	//
	// Here is an example:
	//
	// \code
	// // excludeDeclsFromPCH = 1, displayDiagnostics=1
	// Idx = clang_createIndex(1, 1);
	//
	// // IndexTest.pch was produced with the following command:
	// // "clang -x c IndexTest.h -emit-ast -o IndexTest.pch"
	// TU = clang_createTranslationUnit(Idx, "IndexTest.pch");
	//
	// // This will load all the symbols from 'IndexTest.pch'
	// clang_visitChildren(clang_getTranslationUnitCursor(TU),
	// TranslationUnitVisitor, 0);
	// clang_disposeTranslationUnit(TU);
	//
	// // This will load all the symbols from 'IndexTest.c', excluding symbols
	// // from 'IndexTest.pch'.
	// char *args[] = { "-Xclang", "-include-pch=IndexTest.pch" };
	// TU = clang_createTranslationUnitFromSourceFile(Idx, "IndexTest.c", 2, args,
	// 0, 0);
	// clang_visitChildren(clang_getTranslationUnitCursor(TU),
	// TranslationUnitVisitor, 0);
	// clang_disposeTranslationUnit(TU);
	// \endcode
	//
	// This process of creating the 'pch', loading it separately, and using it (via
	// -include-pch) allows 'excludeDeclsFromPCH' to remove redundant callbacks
	// (which gives the indexer the same performance benefit as the compiler).
	purego_func_clang_createIndex func(
		excludeDeclarationsFromPCH int32,
		displayDiagnostics int32,
	) uintptr
	// Destroy the given index.
	//
	// The index must not be destroyed until all of the translation units created
	// within that index have been destroyed.
	purego_func_clang_disposeIndex func(
		index uintptr,
	)
	// Determine the number of diagnostics produced for the given
	// translation unit.
	purego_func_clang_getNumDiagnostics func(
		Unit uintptr,
	) uint32
	// Same as \c clang_parseTranslationUnit2, but returns
	// the \c CXTranslationUnit instead of an error code.  In case of an error this
	// routine returns a \c NULL \c CXTranslationUnit, without further detailed
	// error codes.
	purego_func_clang_parseTranslationUnit func(
		CIdx uintptr,
		source_filename string,
		command_line_args uintptr,
		num_command_line_args int32,
		unsaved_files uintptr,
		num_unsaved_files uint32,
		options uint32,
	) uintptr
	// Destroy the specified CXTranslationUnit object.
	purego_func_clang_disposeTranslationUnit func(
		arg1 uintptr,
	)
)

func purego_clang_register_functions(handle uintptr) error {
	purego_func_clang_createIndex_symbol, err := purego.Dlsym(handle, "clang_createIndex")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_createIndex: %w", err)
	}
	purego.RegisterFunc(&purego_func_clang_createIndex, purego_func_clang_createIndex_symbol)
	purego_func_clang_disposeIndex_symbol, err := purego.Dlsym(handle, "clang_disposeIndex")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_disposeIndex: %w", err)
	}
	purego.RegisterFunc(&purego_func_clang_disposeIndex, purego_func_clang_disposeIndex_symbol)
	purego_func_clang_getNumDiagnostics_symbol, err := purego.Dlsym(handle, "clang_getNumDiagnostics")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_getNumDiagnostics: %w", err)
	}
	purego.RegisterFunc(&purego_func_clang_getNumDiagnostics, purego_func_clang_getNumDiagnostics_symbol)
	purego_func_clang_parseTranslationUnit_symbol, err := purego.Dlsym(handle, "clang_parseTranslationUnit")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_parseTranslationUnit: %w", err)
	}
	purego.RegisterFunc(&purego_func_clang_parseTranslationUnit, purego_func_clang_parseTranslationUnit_symbol)
	purego_func_clang_disposeTranslationUnit_symbol, err := purego.Dlsym(handle, "clang_disposeTranslationUnit")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_disposeTranslationUnit: %w", err)
	}
	purego.RegisterFunc(&purego_func_clang_disposeTranslationUnit, purego_func_clang_disposeTranslationUnit_symbol)
	return nil
}
