// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

type (
	// An "index" that consists of a set of translation units that would
	// typically be linked together into an executable or library.
	// C: void *
	CXIndex = uintptr
	// A single translation unit, which resides in an index.
	// C: struct CXTranslationUnitImpl *
	CXTranslationUnit uintptr
	// A cursor representing some element in the abstract syntax tree for
	// a translation unit.
	//
	// The cursor abstraction unifies the different kinds of entities in a
	// program--declaration, statements, expressions, references to declarations,
	// etc.--under a single "cursor" abstraction with a common set of operations.
	// Common operation for a cursor include: getting the physical location in
	// a source file where the cursor points, getting the name associated with a
	// cursor, and retrieving cursors for any child nodes of a particular cursor.
	//
	// Cursors can be produced in two specific ways.
	// clang_getTranslationUnitCursor() produces a cursor for a translation unit,
	// from which one can use clang_visitChildren() to explore the rest of the
	// translation unit. clang_getCursor() maps from a physical source location
	// to the entity that resides at that location, allowing one to map from the
	// source code into the AST.
	CXCursor struct {
		kind  int32
		xdata int32
		data  [3]uintptr
	}
	// The type of an element in the abstract syntax tree.
	CXType struct {
		kind int32
		_    [4]byte
		data [2]uintptr
	}
	// Describes a kind of token.
	// C: enum CXTokenKind
	CXTokenKind = int32
	// Describes a single preprocessing token.
	CXToken struct {
		int_data [4]uint32
		// C: void *
		ptr_data uintptr
	}
	// A character string.
	//
	// The \c CXString type is used to return strings from the interface when
	// the ownership of that string might differ from one call to the next.
	// Use \c clang_getCString() to retrieve the string data and, once finished
	// with the string data, call \c clang_disposeString() to free the string.
	CXString struct {
		// C: const void *
		data          uintptr
		private_flags uint32
		_             [4]byte
	}
	// Identifies a specific source location within a translation
	// unit.
	//
	// Use clang_getExpansionLocation() or clang_getSpellingLocation()
	// to map a source location to a particular file, line, and column.
	CXSourceLocation struct {
		ptr_data [2]uintptr
		int_data uint32
		_        [4]byte
	}
	// Identifies a half-open character range in the source code.
	//
	// Use clang_getRangeStart() and clang_getRangeEnd() to retrieve the
	// starting and end locations from a source range, respectively.
	CXSourceRange struct {
		ptr_data       [2]uintptr
		begin_int_data uint32
		end_int_data   uint32
	}
	// A particular source file that is part of a translation unit.
	// C: void *
	CXFile = uintptr
)

const (
	// Used to indicate that the parser should construct a "detailed"
	// preprocessing record, including all macro definitions and instantiations.
	//
	// Constructing a detailed preprocessing record requires more memory
	// and time to parse, since the information contained in the record
	// is usually not retained. However, it can be useful for
	// applications that require more detailed information about the
	// behavior of the preprocessor.
	CXTranslationUnit_DetailedPreprocessingRecord = 1
	// Used to indicate that function/method bodies should be skipped while
	// parsing.
	//
	// This option can be used to search for declarations/definitions while
	// ignoring the usages.
	CXTranslationUnit_SkipFunctionBodies = 64
	// A C or C++ struct.
	CXCursor_StructDecl = 2
	// A C or C++ union.
	CXCursor_UnionDecl = 3
	// An enumeration.
	CXCursor_EnumDecl = 5
	// A field (in C) or non-static data member (in C++) in a
	// struct, union, or C++ class.
	CXCursor_FieldDecl = 6
	// An enumerator constant.
	CXCursor_EnumConstantDecl = 7
	// A function.
	CXCursor_FunctionDecl = 8
	// A variable.
	CXCursor_VarDecl = 9
	// A function or method parameter.
	CXCursor_ParmDecl = 10
	// A typedef.
	CXCursor_TypedefDecl = 20
	// Cursor that represents the translation unit itself.
	//
	// The translation unit cursor exists primarily to act as the root
	// cursor for traversing the contents of a translation unit.
	CXCursor_TranslationUnit = 350
	// An attribute whose specific kind is not exposed via this
	// interface.
	CXCursor_MacroDefinition = 501
	// A type whose specific kind is not exposed via this
	// interface.
	CXType_Void = 2
	// A type whose specific kind is not exposed via this
	// interface.
	CXType_Bool = 3
	// A type whose specific kind is not exposed via this
	// interface.
	CXType_Char_U = 4
	// A type whose specific kind is not exposed via this
	// interface.
	CXType_UChar = 5
	// A type whose specific kind is not exposed via this
	// interface.
	CXType_UShort = 8
	// A type whose specific kind is not exposed via this
	// interface.
	CXType_UInt = 9
	// A type whose specific kind is not exposed via this
	// interface.
	CXType_ULong = 10
	// A type whose specific kind is not exposed via this
	// interface.
	CXType_ULongLong = 11
	// A type whose specific kind is not exposed via this
	// interface.
	CXType_Char_S = 13
	// A type whose specific kind is not exposed via this
	// interface.
	CXType_SChar = 14
	// A type whose specific kind is not exposed via this
	// interface.
	CXType_Short = 16
	// A type whose specific kind is not exposed via this
	// interface.
	CXType_Int = 17
	// A type whose specific kind is not exposed via this
	// interface.
	CXType_Long = 18
	// A type whose specific kind is not exposed via this
	// interface.
	CXType_LongLong = 19
	// A type whose specific kind is not exposed via this
	// interface.
	CXType_Float = 21
	// A type whose specific kind is not exposed via this
	// interface.
	CXType_Double = 22
	// A type whose specific kind is not exposed via this
	// interface.
	CXType_Pointer = 101
	// A type whose specific kind is not exposed via this
	// interface.
	CXType_Record = 105
	// A type whose specific kind is not exposed via this
	// interface.
	CXType_Enum = 106
	// A type whose specific kind is not exposed via this
	// interface.
	CXType_Typedef = 107
	// A type whose specific kind is not exposed via this
	// interface.
	CXType_FunctionNoProto = 110
	// A type whose specific kind is not exposed via this
	// interface.
	CXType_FunctionProto = 111
	// A type whose specific kind is not exposed via this
	// interface.
	CXType_ConstantArray = 112
	CX_SC_Extern         = 2
	// Terminates the cursor traversal.
	CXChildVisit_Break = 0
	// Continues the cursor traversal with the next sibling of
	// the cursor just visited, without visiting its children.
	CXChildVisit_Continue = 1
	// Recursively traverse the children of this cursor, using
	// the same visitor and client data.
	CXChildVisit_Recurse = 2
	// A token that contains some kind of punctuation.
	CXToken_Punctuation = 0
	// A language keyword.
	CXToken_Keyword = 1
	// An identifier (that is not a keyword).
	CXToken_Identifier = 2
	// A numeric, string, or character literal.
	CXToken_Literal = 3
	// A comment.
	CXToken_Comment = 4
)

var (
	// Provides a shared context for creating translation units.
	//
	// It provides two options:
	//
	// - excludeDeclarationsFromPCH: When non-zero, allows enumeration of "local"
	// declarations (when loading any new translation units). A "local" declaration
	// is one that belongs in the translation unit itself and not in a precompiled
	// header that was used by the translation unit. If zero, all declarations
	// will be enumerated.
	//
	// Here is an example:
	//
	// \code
	// // excludeDeclsFromPCH = 1, displayDiagnostics=1
	// Idx = clang_createIndex(1, 1);
	//
	// // IndexTest.pch was produced with the following command:
	// // "clang -x c IndexTest.h -emit-ast -o IndexTest.pch"
	// TU = clang_createTranslationUnit(Idx, "IndexTest.pch");
	//
	// // This will load all the symbols from 'IndexTest.pch'
	// clang_visitChildren(clang_getTranslationUnitCursor(TU),
	// TranslationUnitVisitor, 0);
	// clang_disposeTranslationUnit(TU);
	//
	// // This will load all the symbols from 'IndexTest.c', excluding symbols
	// // from 'IndexTest.pch'.
	// char *args[] = { "-Xclang", "-include-pch=IndexTest.pch" };
	// TU = clang_createTranslationUnitFromSourceFile(Idx, "IndexTest.c", 2, args,
	// 0, 0);
	// clang_visitChildren(clang_getTranslationUnitCursor(TU),
	// TranslationUnitVisitor, 0);
	// clang_disposeTranslationUnit(TU);
	// \endcode
	//
	// This process of creating the 'pch', loading it separately, and using it (via
	// -include-pch) allows 'excludeDeclsFromPCH' to remove redundant callbacks
	// (which gives the indexer the same performance benefit as the compiler).
	clang_createIndex func(
		excludeDeclarationsFromPCH int32,
		displayDiagnostics int32,
		// C: CXIndex
	) uintptr
	// Destroy the given index.
	//
	// The index must not be destroyed until all of the translation units created
	// within that index have been destroyed.
	clang_disposeIndex func(
		// C: CXIndex
		index uintptr,
	)
	// Retrieve a file handle within the given translation unit.
	//
	// \param tu the translation unit
	//
	// \param file_name the name of the file.
	//
	// \returns the file handle for the named file in the translation unit \p tu,
	// or a NULL file handle if the file was not a part of this translation unit.
	clang_getFile func(
		tu CXTranslationUnit,
		file_name string,
		// C: CXFile
	) uintptr
	// Retrieves the source location associated with a given file/line/column
	// in a particular translation unit.
	clang_getLocation func(
		tu CXTranslationUnit,
		// C: CXFile
		file uintptr,
		line uint32,
		column uint32,
	) CXSourceLocation
	// Determine the number of diagnostics produced for the given
	// translation unit.
	clang_getNumDiagnostics func(
		Unit CXTranslationUnit,
	) uint32
	// Same as \c clang_parseTranslationUnit2, but returns
	// the \c CXTranslationUnit instead of an error code.  In case of an error this
	// routine returns a \c NULL \c CXTranslationUnit, without further detailed
	// error codes.
	clang_parseTranslationUnit func(
		// C: CXIndex
		CIdx uintptr,
		source_filename string,
		// C: const char *const *
		command_line_args uintptr,
		num_command_line_args int32,
		// C: struct CXUnsavedFile *
		unsaved_files uintptr,
		num_unsaved_files uint32,
		options uint32,
	) CXTranslationUnit
	// Destroy the specified CXTranslationUnit object.
	clang_disposeTranslationUnit func(
		arg1 CXTranslationUnit,
	)
	// Retrieve the cursor that represents the given translation unit.
	//
	// The translation unit cursor can be used to start traversing the
	// various declarations within the given translation unit.
	clang_getTranslationUnitCursor func(
		arg1 CXTranslationUnit,
	) CXCursor
	// Retrieve the kind of the given cursor.
	clang_getCursorKind func(
		arg1 CXCursor,
	) int32
	// Map a source location to the cursor that describes the entity at that
	// location in the source code.
	//
	// clang_getCursor() maps an arbitrary source location within a translation
	// unit down to the most specific cursor that describes the entity at that
	// location. For example, given an expression \c x + y, invoking
	// clang_getCursor() with a source location pointing to "x" will return the
	// cursor for "x"; similarly for "y". If the cursor points anywhere between
	// "x" or "y" (e.g., on the + or the whitespace around it), clang_getCursor()
	// will return a cursor referring to the "+" expression.
	//
	// \returns a cursor representing the entity at the given source location, or
	// a NULL cursor if no such entity can be found.
	clang_getCursor func(
		arg1 CXTranslationUnit,
		arg2 CXSourceLocation,
	) CXCursor
	// Retrieve the physical location of the source constructor referenced
	// by the given cursor.
	//
	// The location of a declaration is typically the location of the name of that
	// declaration, where the name of that declaration would occur if it is
	// unnamed, or some keyword that introduces that particular declaration.
	// The location of a reference is where that reference occurs within the
	// source code.
	clang_getCursorLocation func(
		arg1 CXCursor,
	) CXSourceLocation
	// Retrieve the physical extent of the source construct referenced by
	// the given cursor.
	//
	// The extent of a cursor starts with the file/line/column pointing at the
	// first character within the source construct that the cursor refers to and
	// ends with the last character within that source construct. For a
	// declaration, the extent covers the declaration itself. For a reference,
	// the extent covers the location of the reference (e.g., where the referenced
	// entity was actually used).
	clang_getCursorExtent func(
		arg1 CXCursor,
	) CXSourceRange
	// Retrieve the type of a CXCursor (if any).
	clang_getCursorType func(
		C CXCursor,
	) CXType
	// Pretty-print the underlying type using the rules of the
	// language of the translation unit from which it came.
	//
	// If the type is invalid, an empty string is returned.
	clang_getTypeSpelling func(
		CT CXType,
	) CXString
	// Retrieve the underlying type of a typedef declaration.
	//
	// If the cursor does not reference a typedef declaration, an invalid type is
	// returned.
	clang_getTypedefDeclUnderlyingType func(
		C CXCursor,
	) CXType
	// Retrieve the number of non-variadic arguments associated with a given
	// cursor.
	//
	// The number of arguments can be determined for calls as well as for
	// declarations of functions or methods. For other cursors -1 is returned.
	clang_Cursor_getNumArguments func(
		C CXCursor,
	) int32
	// Retrieve the argument cursor of a function or method.
	//
	// The argument cursor can be determined for calls as well as for declarations
	// of functions or methods. For other cursors and for invalid indices, an
	// invalid cursor is returned.
	clang_Cursor_getArgument func(
		C CXCursor,
		i uint32,
	) CXCursor
	// Return the canonical type for a CXType.
	//
	// Clang's type system explicitly models typedefs and all the ways
	// a specific type can be represented.  The canonical type is the underlying
	// type with all the "sugar" removed.  For example, if 'T' is a typedef
	// for 'int', the canonical type for 'T' would be 'int'.
	clang_getCanonicalType func(
		T CXType,
	) CXType
	// Determine whether a CXType has the "const" qualifier set,
	// without looking through typedefs that may have added "const" at a
	// different level.
	clang_isConstQualifiedType func(
		T CXType,
	) uint32
	// Determine whether a  CXCursor that is a macro, is
	// function like.
	clang_Cursor_isMacroFunctionLike func(
		C CXCursor,
	) uint32
	// Determine whether a  CXCursor that is a macro, is a
	// builtin one.
	clang_Cursor_isMacroBuiltin func(
		C CXCursor,
	) uint32
	// For pointer types, returns the type of the pointee.
	clang_getPointeeType func(
		T CXType,
	) CXType
	// Return the cursor for the declaration of the given type.
	clang_getTypeDeclaration func(
		T CXType,
	) CXCursor
	// Retrieve the spelling of a given CXTypeKind.
	clang_getTypeKindSpelling func(
		K int32,
	) CXString
	// Retrieve the return type associated with a given cursor.
	//
	// This only returns a valid type if the cursor refers to a function or method.
	clang_getCursorResultType func(
		C CXCursor,
	) CXType
	// Return the alignment of a type in bytes as per C++[expr.alignof]
	// standard.
	//
	// If the type declaration is invalid, CXTypeLayoutError_Invalid is returned.
	// If the type declaration is an incomplete type, CXTypeLayoutError_Incomplete
	// is returned.
	// If the type declaration is a dependent type, CXTypeLayoutError_Dependent is
	// returned.
	// If the type declaration is not a constant size type,
	// CXTypeLayoutError_NotConstantSize is returned.
	clang_Type_getAlignOf func(
		T CXType,
	) int64
	// Return the size of a type in bytes as per C++[expr.sizeof] standard.
	//
	// If the type declaration is invalid, CXTypeLayoutError_Invalid is returned.
	// If the type declaration is an incomplete type, CXTypeLayoutError_Incomplete
	// is returned.
	// If the type declaration is a dependent type, CXTypeLayoutError_Dependent is
	// returned.
	clang_Type_getSizeOf func(
		T CXType,
	) int64
	// Returns the storage class for a function or variable declaration.
	//
	// If the passed in Cursor is not a function or variable declaration,
	// CX_SC_Invalid is returned else the storage class.
	clang_Cursor_getStorageClass func(
		arg1 CXCursor,
	) int32
	// Visit the children of a particular cursor.
	//
	// This function visits all the direct children of the given cursor,
	// invoking the given \p visitor function with the cursors of each
	// visited child. The traversal may be recursive, if the visitor returns
	// \c CXChildVisit_Recurse. The traversal may also be ended prematurely, if
	// the visitor returns \c CXChildVisit_Break.
	//
	// \param parent the cursor whose child may be visited. All kinds of
	// cursors can be visited, including invalid cursors (which, by
	// definition, have no children).
	//
	// \param visitor the visitor function that will be invoked for each
	// child of \p parent.
	//
	// \param client_data pointer data supplied by the client, which will
	// be passed to the visitor each time it is invoked.
	//
	// \returns a non-zero value if the traversal was terminated
	// prematurely by the visitor returning \c CXChildVisit_Break.
	clang_visitChildren func(
		parent CXCursor,
		// C: CXCursorVisitor
		visitor uintptr,
		// C: CXClientData
		client_data uintptr,
	) uint32
	// Retrieve a name for the entity referenced by this cursor.
	clang_getCursorSpelling func(
		arg1 CXCursor,
	) CXString
	// Determine whether the declaration pointed to by this cursor
	// is also a definition of that entity.
	clang_isCursorDefinition func(
		arg1 CXCursor,
	) uint32
	// Given a cursor that represents a declaration, return the associated
	// comment text, including comment markers.
	clang_Cursor_getRawCommentText func(
		C CXCursor,
	) CXString
	// Determine the kind of the given token.
	clang_getTokenKind func(
		arg1 CXToken,
	) int32
	// Determine the spelling of the given token.
	//
	// The spelling of a token is the textual representation of that token, e.g.,
	// the text of an identifier or keyword.
	clang_getTokenSpelling func(
		arg1 CXTranslationUnit,
		arg2 CXToken,
	) CXString
	// Tokenize the source code described by the given range into raw
	// lexical tokens.
	//
	// \param TU the translation unit whose text is being tokenized.
	//
	// \param Range the source range in which text should be tokenized. All of the
	// tokens produced by tokenization will fall within this source range,
	//
	// \param Tokens this pointer will be set to point to the array of tokens
	// that occur within the given source range. The returned pointer must be
	// freed with clang_disposeTokens() before the translation unit is destroyed.
	//
	// \param NumTokens will be set to the number of tokens in the \c *Tokens
	// array.
	clang_tokenize func(
		TU CXTranslationUnit,
		Range CXSourceRange,
		Tokens **CXToken,
		NumTokens *uint32,
	)
	// Free the given set of tokens.
	clang_disposeTokens func(
		TU CXTranslationUnit,
		Tokens *CXToken,
		NumTokens uint32,
	)
	// \defgroup CINDEX_DEBUG Debugging facilities
	//
	// These routines are used for testing and debugging, only, and should not
	// be relied upon.
	//
	// @{
	clang_getCursorKindSpelling func(
		Kind int32,
	) CXString
	// Retrieve the character data associated with the given string.
	//
	// The returned data is a reference and not owned by the user. This data
	// is only valid while the `CXString` is valid. This function is similar
	// to `std::string::c_str()`.
	clang_getCString func(
		string CXString,
	) string
	// Free the given string.
	clang_disposeString func(
		string CXString,
	)
	// Retrieve the file, line, column, and offset represented by
	// the given source location.
	//
	// If the location refers into a macro expansion, retrieves the
	// location of the macro expansion.
	//
	// \param location the location within a source file that will be decomposed
	// into its parts.
	//
	// \param file [out] if non-NULL, will be set to the file to which the given
	// source location points.
	//
	// \param line [out] if non-NULL, will be set to the line to which the given
	// source location points.
	//
	// \param column [out] if non-NULL, will be set to the column to which the given
	// source location points.
	//
	// \param offset [out] if non-NULL, will be set to the offset into the
	// buffer to which the given source location points.
	clang_getExpansionLocation func(
		location CXSourceLocation,
		// C: CXFile *
		file uintptr,
		line *uint32,
		column *uint32,
		offset *uint32,
	)
	// Retrieve the complete file and path name of the given file.
	clang_getFileName func(
		// C: CXFile
		SFile uintptr,
	) CXString
)

func clang_register_functions(handle uintptr) error {
	clang_createIndex_symbol, err := purego.Dlsym(handle, "clang_createIndex")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_createIndex: %w", err)
	}
	purego.RegisterFunc(&clang_createIndex, clang_createIndex_symbol)
	clang_disposeIndex_symbol, err := purego.Dlsym(handle, "clang_disposeIndex")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_disposeIndex: %w", err)
	}
	purego.RegisterFunc(&clang_disposeIndex, clang_disposeIndex_symbol)
	clang_getFile_symbol, err := purego.Dlsym(handle, "clang_getFile")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_getFile: %w", err)
	}
	purego.RegisterFunc(&clang_getFile, clang_getFile_symbol)
	clang_getLocation_symbol, err := purego.Dlsym(handle, "clang_getLocation")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_getLocation: %w", err)
	}
	purego.RegisterFunc(&clang_getLocation, clang_getLocation_symbol)
	clang_getNumDiagnostics_symbol, err := purego.Dlsym(handle, "clang_getNumDiagnostics")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_getNumDiagnostics: %w", err)
	}
	purego.RegisterFunc(&clang_getNumDiagnostics, clang_getNumDiagnostics_symbol)
	clang_parseTranslationUnit_symbol, err := purego.Dlsym(handle, "clang_parseTranslationUnit")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_parseTranslationUnit: %w", err)
	}
	purego.RegisterFunc(&clang_parseTranslationUnit, clang_parseTranslationUnit_symbol)
	clang_disposeTranslationUnit_symbol, err := purego.Dlsym(handle, "clang_disposeTranslationUnit")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_disposeTranslationUnit: %w", err)
	}
	purego.RegisterFunc(&clang_disposeTranslationUnit, clang_disposeTranslationUnit_symbol)
	clang_getTranslationUnitCursor_symbol, err := purego.Dlsym(handle, "clang_getTranslationUnitCursor")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_getTranslationUnitCursor: %w", err)
	}
	purego.RegisterFunc(&clang_getTranslationUnitCursor, clang_getTranslationUnitCursor_symbol)
	clang_getCursorKind_symbol, err := purego.Dlsym(handle, "clang_getCursorKind")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_getCursorKind: %w", err)
	}
	purego.RegisterFunc(&clang_getCursorKind, clang_getCursorKind_symbol)
	clang_getCursor_symbol, err := purego.Dlsym(handle, "clang_getCursor")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_getCursor: %w", err)
	}
	purego.RegisterFunc(&clang_getCursor, clang_getCursor_symbol)
	clang_getCursorLocation_symbol, err := purego.Dlsym(handle, "clang_getCursorLocation")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_getCursorLocation: %w", err)
	}
	purego.RegisterFunc(&clang_getCursorLocation, clang_getCursorLocation_symbol)
	clang_getCursorExtent_symbol, err := purego.Dlsym(handle, "clang_getCursorExtent")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_getCursorExtent: %w", err)
	}
	purego.RegisterFunc(&clang_getCursorExtent, clang_getCursorExtent_symbol)
	clang_getCursorType_symbol, err := purego.Dlsym(handle, "clang_getCursorType")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_getCursorType: %w", err)
	}
	purego.RegisterFunc(&clang_getCursorType, clang_getCursorType_symbol)
	clang_getTypeSpelling_symbol, err := purego.Dlsym(handle, "clang_getTypeSpelling")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_getTypeSpelling: %w", err)
	}
	purego.RegisterFunc(&clang_getTypeSpelling, clang_getTypeSpelling_symbol)
	clang_getTypedefDeclUnderlyingType_symbol, err := purego.Dlsym(handle, "clang_getTypedefDeclUnderlyingType")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_getTypedefDeclUnderlyingType: %w", err)
	}
	purego.RegisterFunc(&clang_getTypedefDeclUnderlyingType, clang_getTypedefDeclUnderlyingType_symbol)
	clang_Cursor_getNumArguments_symbol, err := purego.Dlsym(handle, "clang_Cursor_getNumArguments")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_Cursor_getNumArguments: %w", err)
	}
	purego.RegisterFunc(&clang_Cursor_getNumArguments, clang_Cursor_getNumArguments_symbol)
	clang_Cursor_getArgument_symbol, err := purego.Dlsym(handle, "clang_Cursor_getArgument")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_Cursor_getArgument: %w", err)
	}
	purego.RegisterFunc(&clang_Cursor_getArgument, clang_Cursor_getArgument_symbol)
	clang_getCanonicalType_symbol, err := purego.Dlsym(handle, "clang_getCanonicalType")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_getCanonicalType: %w", err)
	}
	purego.RegisterFunc(&clang_getCanonicalType, clang_getCanonicalType_symbol)
	clang_isConstQualifiedType_symbol, err := purego.Dlsym(handle, "clang_isConstQualifiedType")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_isConstQualifiedType: %w", err)
	}
	purego.RegisterFunc(&clang_isConstQualifiedType, clang_isConstQualifiedType_symbol)
	clang_Cursor_isMacroFunctionLike_symbol, err := purego.Dlsym(handle, "clang_Cursor_isMacroFunctionLike")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_Cursor_isMacroFunctionLike: %w", err)
	}
	purego.RegisterFunc(&clang_Cursor_isMacroFunctionLike, clang_Cursor_isMacroFunctionLike_symbol)
	clang_Cursor_isMacroBuiltin_symbol, err := purego.Dlsym(handle, "clang_Cursor_isMacroBuiltin")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_Cursor_isMacroBuiltin: %w", err)
	}
	purego.RegisterFunc(&clang_Cursor_isMacroBuiltin, clang_Cursor_isMacroBuiltin_symbol)
	clang_getPointeeType_symbol, err := purego.Dlsym(handle, "clang_getPointeeType")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_getPointeeType: %w", err)
	}
	purego.RegisterFunc(&clang_getPointeeType, clang_getPointeeType_symbol)
	clang_getTypeDeclaration_symbol, err := purego.Dlsym(handle, "clang_getTypeDeclaration")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_getTypeDeclaration: %w", err)
	}
	purego.RegisterFunc(&clang_getTypeDeclaration, clang_getTypeDeclaration_symbol)
	clang_getTypeKindSpelling_symbol, err := purego.Dlsym(handle, "clang_getTypeKindSpelling")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_getTypeKindSpelling: %w", err)
	}
	purego.RegisterFunc(&clang_getTypeKindSpelling, clang_getTypeKindSpelling_symbol)
	clang_getCursorResultType_symbol, err := purego.Dlsym(handle, "clang_getCursorResultType")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_getCursorResultType: %w", err)
	}
	purego.RegisterFunc(&clang_getCursorResultType, clang_getCursorResultType_symbol)
	clang_Type_getAlignOf_symbol, err := purego.Dlsym(handle, "clang_Type_getAlignOf")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_Type_getAlignOf: %w", err)
	}
	purego.RegisterFunc(&clang_Type_getAlignOf, clang_Type_getAlignOf_symbol)
	clang_Type_getSizeOf_symbol, err := purego.Dlsym(handle, "clang_Type_getSizeOf")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_Type_getSizeOf: %w", err)
	}
	purego.RegisterFunc(&clang_Type_getSizeOf, clang_Type_getSizeOf_symbol)
	clang_Cursor_getStorageClass_symbol, err := purego.Dlsym(handle, "clang_Cursor_getStorageClass")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_Cursor_getStorageClass: %w", err)
	}
	purego.RegisterFunc(&clang_Cursor_getStorageClass, clang_Cursor_getStorageClass_symbol)
	clang_visitChildren_symbol, err := purego.Dlsym(handle, "clang_visitChildren")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_visitChildren: %w", err)
	}
	purego.RegisterFunc(&clang_visitChildren, clang_visitChildren_symbol)
	clang_getCursorSpelling_symbol, err := purego.Dlsym(handle, "clang_getCursorSpelling")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_getCursorSpelling: %w", err)
	}
	purego.RegisterFunc(&clang_getCursorSpelling, clang_getCursorSpelling_symbol)
	clang_isCursorDefinition_symbol, err := purego.Dlsym(handle, "clang_isCursorDefinition")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_isCursorDefinition: %w", err)
	}
	purego.RegisterFunc(&clang_isCursorDefinition, clang_isCursorDefinition_symbol)
	clang_Cursor_getRawCommentText_symbol, err := purego.Dlsym(handle, "clang_Cursor_getRawCommentText")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_Cursor_getRawCommentText: %w", err)
	}
	purego.RegisterFunc(&clang_Cursor_getRawCommentText, clang_Cursor_getRawCommentText_symbol)
	clang_getTokenKind_symbol, err := purego.Dlsym(handle, "clang_getTokenKind")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_getTokenKind: %w", err)
	}
	purego.RegisterFunc(&clang_getTokenKind, clang_getTokenKind_symbol)
	clang_getTokenSpelling_symbol, err := purego.Dlsym(handle, "clang_getTokenSpelling")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_getTokenSpelling: %w", err)
	}
	purego.RegisterFunc(&clang_getTokenSpelling, clang_getTokenSpelling_symbol)
	clang_tokenize_symbol, err := purego.Dlsym(handle, "clang_tokenize")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_tokenize: %w", err)
	}
	purego.RegisterFunc(&clang_tokenize, clang_tokenize_symbol)
	clang_disposeTokens_symbol, err := purego.Dlsym(handle, "clang_disposeTokens")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_disposeTokens: %w", err)
	}
	purego.RegisterFunc(&clang_disposeTokens, clang_disposeTokens_symbol)
	clang_getCursorKindSpelling_symbol, err := purego.Dlsym(handle, "clang_getCursorKindSpelling")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_getCursorKindSpelling: %w", err)
	}
	purego.RegisterFunc(&clang_getCursorKindSpelling, clang_getCursorKindSpelling_symbol)
	clang_getCString_symbol, err := purego.Dlsym(handle, "clang_getCString")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_getCString: %w", err)
	}
	purego.RegisterFunc(&clang_getCString, clang_getCString_symbol)
	clang_disposeString_symbol, err := purego.Dlsym(handle, "clang_disposeString")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_disposeString: %w", err)
	}
	purego.RegisterFunc(&clang_disposeString, clang_disposeString_symbol)
	clang_getExpansionLocation_symbol, err := purego.Dlsym(handle, "clang_getExpansionLocation")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_getExpansionLocation: %w", err)
	}
	purego.RegisterFunc(&clang_getExpansionLocation, clang_getExpansionLocation_symbol)
	clang_getFileName_symbol, err := purego.Dlsym(handle, "clang_getFileName")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_getFileName: %w", err)
	}
	purego.RegisterFunc(&clang_getFileName, clang_getFileName_symbol)
	return nil
}
