// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

type (
	// Doxygen typedef comment.
	purego_type_fixture_doc_type_t = int32 // int
	// Plain typedef comment.
	purego_type_fixture_plain_type_t = int32 // int
)

const (
	// Doxygen enum constant comment.
	purego_const_FIXTURE_DOC_STATUS = 1
	// Plain enum constant comment.
	purego_const_FIXTURE_PLAIN_STATUS = 2
)

var (
	// Doxygen function comment.
	purego_func_fixture_doc_add func(
		lhs int32,
		rhs int32,
	) int32
	// Plain function comment.
	purego_func_fixture_plain_add func(
		lhs int32,
		rhs int32,
	) int32
)

func purego_fixture_lib_register_functions(handle uintptr) error {
	purego_func_fixture_doc_add_symbol, err := purego.Dlsym(handle, "fixture_doc_add")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_doc_add: %w", err)
	}
	purego.RegisterFunc(&purego_func_fixture_doc_add, purego_func_fixture_doc_add_symbol)
	purego_func_fixture_plain_add_symbol, err := purego.Dlsym(handle, "fixture_plain_add")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_plain_add: %w", err)
	}
	purego.RegisterFunc(&purego_func_fixture_plain_add, purego_func_fixture_plain_add_symbol)
	return nil
}

var (
	// Doxygen runtime-var comment.
	purego_var_fixture_doc_counter uintptr
	// Plain runtime-var comment.
	purego_var_fixture_plain_counter uintptr
)

func purego_fixture_lib_load_runtime_vars(handle uintptr) error {
	purego_var_fixture_doc_counter_symbol, err := purego.Dlsym(handle, "fixture_doc_counter")
	if err != nil {
		return fmt.Errorf(
			"purego-gen: failed to resolve runtime var symbol fixture_doc_counter: %w",
			err,
		)
	}
	purego_var_fixture_doc_counter = purego_var_fixture_doc_counter_symbol
	purego_var_fixture_plain_counter_symbol, err := purego.Dlsym(handle, "fixture_plain_counter")
	if err != nil {
		return fmt.Errorf(
			"purego-gen: failed to resolve runtime var symbol fixture_plain_counter: %w",
			err,
		)
	}
	purego_var_fixture_plain_counter = purego_var_fixture_plain_counter_symbol
	return nil
}
