// Code generated by purego-gen; DO NOT EDIT.

package sample

type (
	purego_type_sample_mode_t       = int32
	purego_type_sample_mode_alias_t = int32
	purego_type_sample_callback_t   = uintptr
	purego_type_sample_name_t       = uintptr
	purego_type_sample_context_t    = uintptr
)

const (
	purego_const_sample_mode_off = 0
	purego_const_sample_mode_on  = 1
)
