// Code generated by purego-gen; DO NOT EDIT.

package sample

type (
	purego_type_sample_mode_t       = int32
	purego_type_sample_mode_alias_t = int32
	purego_type_sample_callback_t   = uintptr
	purego_type_sample_name_t       = uintptr
	purego_type_sample_context_t    = uintptr
	purego_type_sample_point_t      = struct {
		left  int32
		right int32
		mode  int32
		label uintptr
	}
	purego_type_sample_point_alias_t = struct {
		left  int32
		right int32
		mode  int32
		label uintptr
	}
)

const (
	purego_const_sample_mode_off = 0
	purego_const_sample_mode_on  = 1
)
