// Code generated by purego-gen; DO NOT EDIT.

package sample

type purego_type_my_int = int32
type purego_type_my_handle = uintptr

var purego_func_add uintptr
var purego_func_reset uintptr

func purego_sample_lib_register_functions(handle uintptr) error {
	_ = handle
	return nil
}
