// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

var (
	fixture_char_pp func(
		// C: char **
		out uintptr,
	)
	fixture_const_char_pp func(
		// C: const char **
		in uintptr,
	)
	fixture_const_char_p_const_p func(
		// C: const char *const *
		args uintptr,
	)
)

func fixture_lib_register_functions(handle uintptr) error {
	fixture_char_pp_symbol, err := purego.Dlsym(handle, "fixture_char_pp")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_char_pp: %w", err)
	}
	purego.RegisterFunc(&fixture_char_pp, fixture_char_pp_symbol)
	fixture_const_char_pp_symbol, err := purego.Dlsym(handle, "fixture_const_char_pp")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_const_char_pp: %w", err)
	}
	purego.RegisterFunc(&fixture_const_char_pp, fixture_const_char_pp_symbol)
	fixture_const_char_p_const_p_symbol, err := purego.Dlsym(handle, "fixture_const_char_p_const_p")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_const_char_p_const_p: %w", err)
	}
	purego.RegisterFunc(&fixture_const_char_p_const_p, fixture_const_char_p_const_p_symbol)
	return nil
}
