// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

type (
	// C: struct fixture_handle
	fixture_handle struct{}
)

var (
	fixture_open func(
		name string,
		out_handle **fixture_handle,
	) int32
)

func fixture_lib_register_functions(handle uintptr) error {
	fixture_open_symbol, err := purego.Dlsym(handle, "fixture_open")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_open: %w", err)
	}
	purego.RegisterFunc(&fixture_open, fixture_open_symbol)
	return nil
}
