// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

type (
	my_union_t struct {
		_ [0]int32
		_ [4]byte
	}
	my_wide_union_t struct {
		_ [0]int64
		_ [8]byte
	}
	// C: union my_byte_union
	my_byte_union_t    [1]byte
	with_union_field_t struct {
		tag   int32
		value struct {
			_ [0]int32
			_ [4]byte
		}
	}
)

func union_get[T any, U any](u *U) T {
	return *(*T)(unsafe.Pointer(u))
}

func union_set[T any, U any](u *U, v T) {
	*(*T)(unsafe.Pointer(u)) = v
}

var (
	use_union func(
		u my_union_t,
	)
)

func fixture_lib_register_functions(handle uintptr) error {
	use_union_symbol, err := purego.Dlsym(handle, "use_union")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol use_union: %w", err)
	}
	purego.RegisterFunc(&use_union, use_union_symbol)
	return nil
}
