// Code generated by purego-gen fixture placeholder; DO NOT EDIT.
//
// This file keeps gopls diagnostics low when reading fixture tests in editor.
// The Python test harness overwrites this file in a temporary directory.

package sample

var (
	purego_func_smoke_increment func()
	purego_func_smoke_reset     func()
	purego_var_smoke_counter    uintptr
)

func purego_sample_lib_register_functions(handle uintptr) error {
	_ = handle
	return nil
}

func purego_sample_lib_load_runtime_vars(handle uintptr) error {
	_ = handle
	return nil
}
