// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

type (
	// C: int
	my_int = int32
	// C: void *
	my_handle = uintptr
	// C: struct not_basic
	not_basic struct{}
)

var (
	add func(
		lhs int32,
		rhs int32,
	) int32
	reset func()
)

func fixture_lib_register_functions(handle uintptr) error {
	add_symbol, err := purego.Dlsym(handle, "add")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol add: %w", err)
	}
	purego.RegisterFunc(&add, add_symbol)
	reset_symbol, err := purego.Dlsym(handle, "reset")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol reset: %w", err)
	}
	purego.RegisterFunc(&reset, reset_symbol)
	return nil
}
