// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

var (
	fixture_uintptr_t_param func(
		value uint64,
	)
)

func fixture_lib_register_functions(handle uintptr) error {
	fixture_uintptr_t_param_symbol, err := purego.Dlsym(handle, "fixture_uintptr_t_param")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_uintptr_t_param: %w", err)
	}
	purego.RegisterFunc(&fixture_uintptr_t_param, fixture_uintptr_t_param_symbol)
	return nil
}
