// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

type (
	// C: struct fixture_ctx
	fixture_ctx struct{}
	// C: struct fixture_val
	fixture_val struct{}
	// C: void (*)(fixture_ctx *, int, fixture_val **)
	fixture_process_fn = uintptr
	// C: void (*)(fixture_ctx *, int, fixture_val **)
	fixture_process_fn_func = func(*fixture_ctx, int32, **fixture_val)
)

func new_fixture_process_fn(fn fixture_process_fn_func) fixture_process_fn {
	return fixture_process_fn(purego.NewCallback(fn))
}

var (
	fixture_process func(
		fn fixture_process_fn,
	) int32
)

func fixture_process_callbacks(
	fn func(*fixture_ctx, int32, **fixture_val),
) int32 {
	fn_callback := uintptr(0)
	if fn != nil {
		fn_callback = purego.NewCallback(fn)
	}
	return fixture_process(
		fn_callback,
	)
}

func fixture_lib_register_functions(handle uintptr) error {
	fixture_process_symbol, err := purego.Dlsym(handle, "fixture_process")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_process: %w", err)
	}
	purego.RegisterFunc(&fixture_process, fixture_process_symbol)
	return nil
}
