// Code generated by purego-gen; DO NOT EDIT.

package libclang

import (
	"fmt"

	"github.com/ebitengine/purego"
)

type (
	purego_type_CXIndex           = uintptr
	purego_type_CXTranslationUnit = uintptr
)

const (
	purego_const_CXTranslationUnit_DetailedPreprocessingRecord = 1
	purego_const_CXTranslationUnit_SkipFunctionBodies          = 64
)

var (
	purego_func_clang_createIndex func(
		excludeDeclarationsFromPCH int32,
		displayDiagnostics int32,
	) uintptr
	purego_func_clang_disposeIndex func(
		index uintptr,
	)
	purego_func_clang_getNumDiagnostics func(
		unit uintptr,
	) uint32
	purego_func_clang_parseTranslationUnit func(
		cidx uintptr,
		sourceFilename string,
		commandLineArgs uintptr,
		numCommandLineArgs int32,
		unsavedFiles uintptr,
		numUnsavedFiles uint32,
		options uint32,
	) uintptr
	purego_func_clang_disposeTranslationUnit func(
		translationUnit uintptr,
	)
)

func purego_clang_register_functions(handle uintptr) error {
	purego_func_clang_createIndex_symbol, err := purego.Dlsym(handle, "clang_createIndex")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_createIndex: %w", err)
	}
	purego.RegisterFunc(&purego_func_clang_createIndex, purego_func_clang_createIndex_symbol)
	purego_func_clang_disposeIndex_symbol, err := purego.Dlsym(handle, "clang_disposeIndex")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_disposeIndex: %w", err)
	}
	purego.RegisterFunc(&purego_func_clang_disposeIndex, purego_func_clang_disposeIndex_symbol)
	purego_func_clang_getNumDiagnostics_symbol, err := purego.Dlsym(handle, "clang_getNumDiagnostics")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_getNumDiagnostics: %w", err)
	}
	purego.RegisterFunc(&purego_func_clang_getNumDiagnostics, purego_func_clang_getNumDiagnostics_symbol)
	purego_func_clang_parseTranslationUnit_symbol, err := purego.Dlsym(handle, "clang_parseTranslationUnit")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_parseTranslationUnit: %w", err)
	}
	purego.RegisterFunc(&purego_func_clang_parseTranslationUnit, purego_func_clang_parseTranslationUnit_symbol)
	purego_func_clang_disposeTranslationUnit_symbol, err := purego.Dlsym(handle, "clang_disposeTranslationUnit")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol clang_disposeTranslationUnit: %w", err)
	}
	purego.RegisterFunc(
		&purego_func_clang_disposeTranslationUnit,
		purego_func_clang_disposeTranslationUnit_symbol,
	)
	return nil
}
