// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

var (
	fixture_describe func(
		code int32,
	) string
)

func fixture_lib_register_functions(handle uintptr) error {
	fixture_describe_symbol, err := purego.Dlsym(handle, "fixture_describe")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_describe: %w", err)
	}
	purego.RegisterFunc(&fixture_describe, fixture_describe_symbol)
	return nil
}
