// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

type (
	// C: void (*)(int)
	on_done_func = func(int32)
)

func new_on_done(fn on_done_func) uintptr {
	return uintptr(purego.NewCallback(fn))
}

var (
	fixture_fn_a func(
		// C: void (*)(int)
		on_done uintptr,
	)
	fixture_fn_b func(
		// C: void (*)(int)
		on_done uintptr,
	)
)

func fixture_fn_a_callbacks(
	on_done on_done_func,
) {
	on_done_callback := uintptr(0)
	if on_done != nil {
		on_done_callback = purego.NewCallback(on_done)
	}
	fixture_fn_a(
		on_done_callback,
	)
}
func fixture_fn_b_callbacks(
	on_done on_done_func,
) {
	on_done_callback := uintptr(0)
	if on_done != nil {
		on_done_callback = purego.NewCallback(on_done)
	}
	fixture_fn_b(
		on_done_callback,
	)
}

func fixture_lib_register_functions(handle uintptr) error {
	fixture_fn_a_symbol, err := purego.Dlsym(handle, "fixture_fn_a")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_fn_a: %w", err)
	}
	purego.RegisterFunc(&fixture_fn_a, fixture_fn_a_symbol)
	fixture_fn_b_symbol, err := purego.Dlsym(handle, "fixture_fn_b")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_fn_b: %w", err)
	}
	purego.RegisterFunc(&fixture_fn_b, fixture_fn_b_symbol)
	return nil
}
