// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

type (
	// C: int
	fixture_mode_t = int32
)

const (
	FIXTURE_STATUS_OK = 0
)

var (
	fixture_add func(
		lhs int32,
		rhs int32,
	) int32
)

func fixture_lib_register_functions(handle uintptr) error {
	fixture_add_symbol, err := purego.Dlsym(handle, "fixture_add")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol fixture_add: %w", err)
	}
	purego.RegisterFunc(&fixture_add, fixture_add_symbol)
	return nil
}

var (
	fixture_counter uintptr
)

func fixture_lib_load_runtime_vars(handle uintptr) error {
	fixture_counter_symbol, err := purego.Dlsym(handle, "fixture_counter")
	if err != nil {
		return fmt.Errorf(
			"purego-gen: failed to resolve runtime var symbol fixture_counter: %w",
			err,
		)
	}
	fixture_counter = fixture_counter_symbol
	return nil
}
