// Code generated by purego-gen; DO NOT EDIT.

package fixture

import (
	"fmt"
	"unsafe"

	"github.com/ebitengine/purego"
)

var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

type (
	// *************************************
	// Explicit context
	// *************************************
	// C: struct ZSTD_CCtx_s
	ZSTD_CCtx struct{}
	// C: struct ZSTD_DCtx_s
	ZSTD_DCtx struct{}
	// *********************************
	// Bulk processing dictionary API
	// ********************************
	// C: struct ZSTD_CDict_s
	ZSTD_CDict struct{}
	// C: struct ZSTD_DDict_s
	ZSTD_DDict struct{}
	// C: enum ZSTD_ErrorCode
	ZSTD_ErrorCode int32
)

const (
	ZSTD_CONTENTSIZE_UNKNOWN uint64 = 18446744073709551615
	ZSTD_CONTENTSIZE_ERROR   uint64 = 18446744073709551614
)

var (
	// ! ZSTD_versionNumber() :
	// Return runtime library version, the value is (MAJOR*100*100 + MINOR*100 + RELEASE).
	ZSTD_versionNumber func() uint32
	// *************************************
	// Simple Core API
	// **************************************/
	// /*! ZSTD_compress() :
	// Compresses `src` content as a single zstd compressed frame into already allocated `dst`.
	// NOTE: Providing `dstCapacity >= ZSTD_compressBound(srcSize)` guarantees that zstd will have
	// enough space to successfully compress the data.
	// @return : compressed size written into `dst` (<= `dstCapacity),
	// or an error code if it fails (which can be tested using ZSTD_isError()).
	ZSTD_compress func(
		// C: void *
		dst uintptr,
		dstCapacity uint64,
		// C: const void *
		src uintptr,
		srcSize uint64,
		compressionLevel int32,
	) uint64
	// ! ZSTD_decompress() :
	// `compressedSize` : must be the _exact_ size of some number of compressed and/or skippable frames.
	// Multiple compressed frames can be decompressed at once with this method.
	// The result will be the concatenation of all decompressed frames, back to back.
	// `dstCapacity` is an upper bound of originalSize to regenerate.
	// First frame's decompressed size can be extracted using ZSTD_getFrameContentSize().
	// If maximum upper bound isn't known, prefer using streaming mode to decompress data.
	// @return : the number of bytes decompressed into `dst` (<= `dstCapacity`),
	// or an errorCode if it fails (which can be tested using ZSTD_isError()).
	ZSTD_decompress func(
		// C: void *
		dst uintptr,
		dstCapacity uint64,
		// C: const void *
		src uintptr,
		compressedSize uint64,
	) uint64
	ZSTD_getFrameContentSize func(
		// C: const void *
		src uintptr,
		srcSize uint64,
	) uint64
	// ! ZSTD_findFrameCompressedSize() : Requires v1.4.0+
	// `src` should point to the start of a ZSTD frame or skippable frame.
	// `srcSize` must be >= first frame size
	// @return : the compressed size of the first frame starting at `src`,
	// suitable to pass as `srcSize` to `ZSTD_decompress` or similar,
	// or an error code if input is invalid
	// Note 1: this method is called _find*() because it's not enough to read the header,
	// it may have to scan through the frame's content, to reach its end.
	// Note 2: this method also works with Skippable Frames. In which case,
	// it returns the size of the complete skippable frame,
	// which is always equal to its content size + 8 bytes for headers.
	ZSTD_findFrameCompressedSize func(
		// C: const void *
		src uintptr,
		srcSize uint64,
	) uint64
	ZSTD_compressBound func(
		srcSize uint64,
	) uint64
	ZSTD_isError func(
		result uint64,
	) uint32
	ZSTD_getErrorCode func(
		functionResult uint64,
	) ZSTD_ErrorCode
	ZSTD_getErrorName func(
		result uint64,
	) string
	ZSTD_minCLevel  func() int32
	ZSTD_maxCLevel  func() int32
	ZSTD_createCCtx func() *ZSTD_CCtx
	ZSTD_freeCCtx   func(
		cctx *ZSTD_CCtx,
	) uint64
	// ! ZSTD_compressCCtx() :
	// Same as ZSTD_compress(), using an explicit ZSTD_CCtx.
	// Important : in order to mirror `ZSTD_compress()` behavior,
	// this function compresses at the requested compression level,
	// __ignoring any other advanced parameter__ .
	// If any advanced parameter was set using the advanced API,
	// they will all be reset. Only @compressionLevel remains.
	ZSTD_compressCCtx func(
		cctx *ZSTD_CCtx,
		// C: void *
		dst uintptr,
		dstCapacity uint64,
		// C: const void *
		src uintptr,
		srcSize uint64,
		compressionLevel int32,
	) uint64
	ZSTD_createDCtx func() *ZSTD_DCtx
	ZSTD_freeDCtx   func(
		dctx *ZSTD_DCtx,
	) uint64
	// ! ZSTD_decompressDCtx() :
	// Same as ZSTD_decompress(),
	// requires an allocated ZSTD_DCtx.
	// Compatible with sticky parameters (see below).
	ZSTD_decompressDCtx func(
		dctx *ZSTD_DCtx,
		// C: void *
		dst uintptr,
		dstCapacity uint64,
		// C: const void *
		src uintptr,
		srcSize uint64,
	) uint64
	// ************************
	// Simple dictionary API
	// **************************/
	// /*! ZSTD_compress_usingDict() :
	// Compression at an explicit compression level using a Dictionary.
	// A dictionary can be any arbitrary data segment (also called a prefix),
	// or a buffer with specified information (see zdict.h).
	// Note : This function loads the dictionary, resulting in significant startup delay.
	// It's intended for a dictionary used only once.
	// Note 2 : When `dict == NULL || dictSize < 8` no dictionary is used.
	ZSTD_compress_usingDict func(
		ctx *ZSTD_CCtx,
		// C: void *
		dst uintptr,
		dstCapacity uint64,
		// C: const void *
		src uintptr,
		srcSize uint64,
		// C: const void *
		dict uintptr,
		dictSize uint64,
		compressionLevel int32,
	) uint64
	// ! ZSTD_decompress_usingDict() :
	// Decompression using a known Dictionary.
	// Dictionary must be identical to the one used during compression.
	// Note : This function loads the dictionary, resulting in significant startup delay.
	// It's intended for a dictionary used only once.
	// Note : When `dict == NULL || dictSize < 8` no dictionary is used.
	ZSTD_decompress_usingDict func(
		dctx *ZSTD_DCtx,
		// C: void *
		dst uintptr,
		dstCapacity uint64,
		// C: const void *
		src uintptr,
		srcSize uint64,
		// C: const void *
		dict uintptr,
		dictSize uint64,
	) uint64
)

func ZSTD_compress_bytes(
	dst uintptr,
	dstCapacity uint64,
	src []byte,
	compressionLevel int32,
) uint64 {
	src_ptr := uintptr(0)
	src_len := src
	if len(src_len) > 0 {
		src_ptr = uintptr(unsafe.Pointer(&src_len[0]))
	}
	return ZSTD_compress(
		dst,
		dstCapacity,
		src_ptr,
		uint64(len(src_len)),
		compressionLevel,
	)
}
func ZSTD_decompress_bytes(
	dst uintptr,
	dstCapacity uint64,
	src []byte,
) uint64 {
	src_ptr := uintptr(0)
	src_len := src
	if len(src_len) > 0 {
		src_ptr = uintptr(unsafe.Pointer(&src_len[0]))
	}
	return ZSTD_decompress(
		dst,
		dstCapacity,
		src_ptr,
		uint64(len(src_len)),
	)
}
func ZSTD_compress_usingDict_bytes(
	ctx *ZSTD_CCtx,
	dst uintptr,
	dstCapacity uint64,
	src []byte,
	dict []byte,
	compressionLevel int32,
) uint64 {
	src_ptr := uintptr(0)
	src_len := src
	dict_ptr := uintptr(0)
	dict_len := dict
	if len(src_len) > 0 {
		src_ptr = uintptr(unsafe.Pointer(&src_len[0]))
	}
	if len(dict_len) > 0 {
		dict_ptr = uintptr(unsafe.Pointer(&dict_len[0]))
	}
	return ZSTD_compress_usingDict(
		ctx,
		dst,
		dstCapacity,
		src_ptr,
		uint64(len(src_len)),
		dict_ptr,
		uint64(len(dict_len)),
		compressionLevel,
	)
}
func ZSTD_decompress_usingDict_bytes(
	dctx *ZSTD_DCtx,
	dst uintptr,
	dstCapacity uint64,
	src []byte,
	dict []byte,
) uint64 {
	src_ptr := uintptr(0)
	src_len := src
	dict_ptr := uintptr(0)
	dict_len := dict
	if len(src_len) > 0 {
		src_ptr = uintptr(unsafe.Pointer(&src_len[0]))
	}
	if len(dict_len) > 0 {
		dict_ptr = uintptr(unsafe.Pointer(&dict_len[0]))
	}
	return ZSTD_decompress_usingDict(
		dctx,
		dst,
		dstCapacity,
		src_ptr,
		uint64(len(src_len)),
		dict_ptr,
		uint64(len(dict_len)),
	)
}
func ZSTD_findFrameCompressedSize_bytes(
	src []byte,
) uint64 {
	src_ptr := uintptr(0)
	src_len := src
	if len(src_len) > 0 {
		src_ptr = uintptr(unsafe.Pointer(&src_len[0]))
	}
	return ZSTD_findFrameCompressedSize(
		src_ptr,
		uint64(len(src_len)),
	)
}
func ZSTD_getFrameContentSize_bytes(
	src []byte,
) uint64 {
	src_ptr := uintptr(0)
	src_len := src
	if len(src_len) > 0 {
		src_ptr = uintptr(unsafe.Pointer(&src_len[0]))
	}
	return ZSTD_getFrameContentSize(
		src_ptr,
		uint64(len(src_len)),
	)
}
func ZSTD_compressCCtx_bytes(
	cctx *ZSTD_CCtx,
	dst uintptr,
	dstCapacity uint64,
	src []byte,
	compressionLevel int32,
) uint64 {
	src_ptr := uintptr(0)
	src_len := src
	if len(src_len) > 0 {
		src_ptr = uintptr(unsafe.Pointer(&src_len[0]))
	}
	return ZSTD_compressCCtx(
		cctx,
		dst,
		dstCapacity,
		src_ptr,
		uint64(len(src_len)),
		compressionLevel,
	)
}
func ZSTD_decompressDCtx_bytes(
	dctx *ZSTD_DCtx,
	dst uintptr,
	dstCapacity uint64,
	src []byte,
) uint64 {
	src_ptr := uintptr(0)
	src_len := src
	if len(src_len) > 0 {
		src_ptr = uintptr(unsafe.Pointer(&src_len[0]))
	}
	return ZSTD_decompressDCtx(
		dctx,
		dst,
		dstCapacity,
		src_ptr,
		uint64(len(src_len)),
	)
}

func zstd_register_functions(handle uintptr) error {
	ZSTD_versionNumber_symbol, err := purego.Dlsym(handle, "ZSTD_versionNumber")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol ZSTD_versionNumber: %w", err)
	}
	purego.RegisterFunc(&ZSTD_versionNumber, ZSTD_versionNumber_symbol)
	ZSTD_compress_symbol, err := purego.Dlsym(handle, "ZSTD_compress")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol ZSTD_compress: %w", err)
	}
	purego.RegisterFunc(&ZSTD_compress, ZSTD_compress_symbol)
	ZSTD_decompress_symbol, err := purego.Dlsym(handle, "ZSTD_decompress")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol ZSTD_decompress: %w", err)
	}
	purego.RegisterFunc(&ZSTD_decompress, ZSTD_decompress_symbol)
	ZSTD_getFrameContentSize_symbol, err := purego.Dlsym(handle, "ZSTD_getFrameContentSize")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol ZSTD_getFrameContentSize: %w", err)
	}
	purego.RegisterFunc(&ZSTD_getFrameContentSize, ZSTD_getFrameContentSize_symbol)
	ZSTD_findFrameCompressedSize_symbol, err := purego.Dlsym(handle, "ZSTD_findFrameCompressedSize")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol ZSTD_findFrameCompressedSize: %w", err)
	}
	purego.RegisterFunc(&ZSTD_findFrameCompressedSize, ZSTD_findFrameCompressedSize_symbol)
	ZSTD_compressBound_symbol, err := purego.Dlsym(handle, "ZSTD_compressBound")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol ZSTD_compressBound: %w", err)
	}
	purego.RegisterFunc(&ZSTD_compressBound, ZSTD_compressBound_symbol)
	ZSTD_isError_symbol, err := purego.Dlsym(handle, "ZSTD_isError")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol ZSTD_isError: %w", err)
	}
	purego.RegisterFunc(&ZSTD_isError, ZSTD_isError_symbol)
	ZSTD_getErrorCode_symbol, err := purego.Dlsym(handle, "ZSTD_getErrorCode")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol ZSTD_getErrorCode: %w", err)
	}
	purego.RegisterFunc(&ZSTD_getErrorCode, ZSTD_getErrorCode_symbol)
	ZSTD_getErrorName_symbol, err := purego.Dlsym(handle, "ZSTD_getErrorName")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol ZSTD_getErrorName: %w", err)
	}
	purego.RegisterFunc(&ZSTD_getErrorName, ZSTD_getErrorName_symbol)
	ZSTD_minCLevel_symbol, err := purego.Dlsym(handle, "ZSTD_minCLevel")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol ZSTD_minCLevel: %w", err)
	}
	purego.RegisterFunc(&ZSTD_minCLevel, ZSTD_minCLevel_symbol)
	ZSTD_maxCLevel_symbol, err := purego.Dlsym(handle, "ZSTD_maxCLevel")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol ZSTD_maxCLevel: %w", err)
	}
	purego.RegisterFunc(&ZSTD_maxCLevel, ZSTD_maxCLevel_symbol)
	ZSTD_createCCtx_symbol, err := purego.Dlsym(handle, "ZSTD_createCCtx")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol ZSTD_createCCtx: %w", err)
	}
	purego.RegisterFunc(&ZSTD_createCCtx, ZSTD_createCCtx_symbol)
	ZSTD_freeCCtx_symbol, err := purego.Dlsym(handle, "ZSTD_freeCCtx")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol ZSTD_freeCCtx: %w", err)
	}
	purego.RegisterFunc(&ZSTD_freeCCtx, ZSTD_freeCCtx_symbol)
	ZSTD_compressCCtx_symbol, err := purego.Dlsym(handle, "ZSTD_compressCCtx")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol ZSTD_compressCCtx: %w", err)
	}
	purego.RegisterFunc(&ZSTD_compressCCtx, ZSTD_compressCCtx_symbol)
	ZSTD_createDCtx_symbol, err := purego.Dlsym(handle, "ZSTD_createDCtx")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol ZSTD_createDCtx: %w", err)
	}
	purego.RegisterFunc(&ZSTD_createDCtx, ZSTD_createDCtx_symbol)
	ZSTD_freeDCtx_symbol, err := purego.Dlsym(handle, "ZSTD_freeDCtx")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol ZSTD_freeDCtx: %w", err)
	}
	purego.RegisterFunc(&ZSTD_freeDCtx, ZSTD_freeDCtx_symbol)
	ZSTD_decompressDCtx_symbol, err := purego.Dlsym(handle, "ZSTD_decompressDCtx")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol ZSTD_decompressDCtx: %w", err)
	}
	purego.RegisterFunc(&ZSTD_decompressDCtx, ZSTD_decompressDCtx_symbol)
	ZSTD_compress_usingDict_symbol, err := purego.Dlsym(handle, "ZSTD_compress_usingDict")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol ZSTD_compress_usingDict: %w", err)
	}
	purego.RegisterFunc(&ZSTD_compress_usingDict, ZSTD_compress_usingDict_symbol)
	ZSTD_decompress_usingDict_symbol, err := purego.Dlsym(handle, "ZSTD_decompress_usingDict")
	if err != nil {
		return fmt.Errorf("purego-gen: failed to resolve function symbol ZSTD_decompress_usingDict: %w", err)
	}
	purego.RegisterFunc(&ZSTD_decompress_usingDict, ZSTD_decompress_usingDict_symbol)
	return nil
}
